#! /usr/bin/env python3

"""Таблица настроек Измерителя-регулятора микропроцессорного 4ТРМ1–ТР."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from owen.device._types import DEVICE

_4TRM1: DEVICE = {
    "modbus": {"ARCHIVE.LAST":         {"type":    "U16", "index": {None: 0x0387}, "dp": None, "precision": 0},
               "ARCHIVE.PERIOD":       {"type":    "U16", "index": {None: 0x0384}, "dp": None, "precision": 0},
               "ARCHIVE.QUANTITY":     {"type":    "U16", "index": {None: 0x0385}, "dp": None, "precision": 0},
               "ARCHIVE.SIZE":         {"type":    "U16", "index": {None: 0x0386}, "dp": None, "precision": 0},
               "BATTERY.STATE":        {"type":    "U16", "index": {None: 0x0322}, "dp": None, "precision": 0},
               "BATTERY.THRESHOLD":    {"type":    "U16", "index": {None: 0x0320}, "dp": None, "precision": 0},
               "BATTERY.VOLTAGE":      {"type":    "U16", "index": {None: 0x0321}, "dp": None, "precision": 0},
               "CLOUD.ACCESS":         {"type":    "U16", "index": {None: 0x02BF}, "dp": None, "precision": 0},
               "CLOUD.CONNECT":        {"type":    "U16", "index": {None: 0x0023}, "dp": None, "precision": 0},
               "CLOUD.ENABLE":         {"type":    "U16", "index": {None: 0x02BD}, "dp": None, "precision": 0},
               "CLOUD.STATUS":         {"type":    "U16", "index": {None: 0x0024}, "dp": None, "precision": 0},
               "CLOUD.WRITING":        {"type":    "U16", "index": {None: 0x02BE}, "dp": None, "precision": 0},
               "DATATIME.DAY":         {"type":     "U8", "index": {None: 0xF078}, "dp": None, "precision": 0},
               "DATATIME.HOUR":        {"type":     "U8", "index": {None: 0xF077}, "dp": None, "precision": 0},
               "DATATIME.MINUTE":      {"type":     "U8", "index": {None: 0xF076}, "dp": None, "precision": 0},
               "DATATIME.MONTH":       {"type":     "U8", "index": {None: 0xF079}, "dp": None, "precision": 0},
               "DATATIME.SECONDS":     {"type":     "U8", "index": {None: 0xF075}, "dp": None, "precision": 0},
               "DATATIME.TIMEZONE":    {"type":    "U16", "index": {None: 0xF073}, "dp": None, "precision": 0},
               "DATATIME.WEEKDAY":     {"type":    "U16", "index": {None: 0xF074}, "dp": None, "precision": 0},
               "DATATIME.YEAR":        {"type":    "U16", "index": {None: 0xF07A}, "dp": None, "precision": 0},
               "DEVICE.APPVER":        {"type":  "STR16", "index": {None: 0xF040}, "dp": None, "precision": 0},
               "DEVICE.BOARDNAME":     {"type":  "STR32", "index": {None: 0xF020}, "dp": None, "precision": 0},
               "DEVICE.BOARDVER":      {"type":  "STR32", "index": {None: 0xF030}, "dp": None, "precision": 0},
               "DEVICE.DEV":           {"type":  "STR32", "index": {None: 0xF000}, "dp": None, "precision": 0},
               "DEVICE.INFO":          {"type":  "STR16", "index": {None: 0xF048}, "dp": None, "precision": 0},
               "DEVICE.NUMBER":        {"type":  "STR32", "index": {None: 0xF084}, "dp": None, "precision": 0},
               "DEVICE.POWER":         {"type":    "U16", "index": {None: 0xEAA1}, "dp": None, "precision": 0},
               "DEVICE.VER":           {"type":  "STR32", "index": {None: 0xF010}, "dp": None, "precision": 0},
               "ETHERNET.APPLY":       {"type":    "U16", "index": {None: 0x0021}, "dp": None, "precision": 0},
               "ETHERNET.DHCP":        {"type":    "U16", "index": {None: 0x0020}, "dp": None, "precision": 0},
               "ETHERNET.DNS1":        {"type":    "U32", "index": {None: 0x000C}, "dp": None, "precision": 0},
               "ETHERNET.DNS2":        {"type":    "U32", "index": {None: 0x000E}, "dp": None, "precision": 0},
               "ETHERNET.GATEWAY":     {"type":    "U32", "index": {None: 0x0018}, "dp": None, "precision": 0},
               "ETHERNET.GET_GATEWAY": {"type":    "U32", "index": {None: 0x001E}, "dp": None, "precision": 0},
               "ETHERNET.GET_IP":      {"type":    "U32", "index": {None: 0x001A}, "dp": None, "precision": 0},
               "ETHERNET.GET_MASK":    {"type":    "U32", "index": {None: 0x001C}, "dp": None, "precision": 0},
               "ETHERNET.IP":          {"type":    "U32", "index": {None: 0x0014}, "dp": None, "precision": 0},
               "ETHERNET.MAC":         {"type": "STR128", "index": {None: 0xF110}, "dp": None, "precision": 0},
               "ETHERNET.MASK":        {"type":    "U32", "index": {None: 0x0016}, "dp": None, "precision": 0},
               "ETHERNET.STATUS":      {"type":    "U16", "index": {None: 0x0022}, "dp": None, "precision": 0},
               "RS485.BAUDRATE":       {"type":    "U16", "index": {None: 0x02EE}, "dp": None, "precision": 0},
               "RS485.DATABITS":       {"type":    "U16", "index": {None: 0x02EF}, "dp": None, "precision": 0},
               "RS485.PARITY":         {"type":    "U16", "index": {None: 0x02F0}, "dp": None, "precision": 0},
               "RS485.SLAVEID":        {"type":    "U16", "index": {None: 0x02F2}, "dp": None, "precision": 0},
               "RS485.STOPBITS":       {"type":    "U16", "index": {None: 0x02F1}, "dp": None, "precision": 0},
               "RTC.MSEC":             {"type":    "U32", "index": {None: 0xF07B}, "dp": None, "precision": 0},
               "RTC.TIMEZONE":         {"type":    "I16", "index": {None: 0xF082}, "dp": None, "precision": 0},
               "RTC.UTC":              {"type":    "U32", "index": {None: 0xF080}, "dp": None, "precision": 0},
               "SLAVE.NOEXCHANGE":     {"type":     "U8", "index": {None: 0xD000}, "dp": None, "precision": 0},
               "SLAVE.TIMEOUT":        {"type":     "U8", "index": {None: 0x02BC}, "dp": None, "precision": 0},
               "USB.FOLDER":           {"type": "STR128", "index": {None: 0xEA57}, "dp": None, "precision": 0},
               "USB.PERCENT":          {"type":     "U8", "index": {None: 0xEA5F}, "dp": None, "precision": 0},
               "USB.STATUS":           {"type":     "U8", "index": {None: 0xEA56}, "dp": None, "precision": 0},

               "DISPLAY.BRGH":     {"type": "U16", "index": {None: 0x0401}, "dp": None, "precision": 0},
               "DISPLAY.CHG.T":    {"type": "U16", "index": {None: 0x03FE}, "dp": None, "precision": 0},
               "DISPLAY.DP.T":     {"type": "U16", "index": {None: 0x03FF}, "dp": None, "precision": 0},
               "DISPLAY.PAR.V":    {"type": "U16", "index": {None: 0x03FC}, "dp": None, "precision": 0},
               "DISPLAY.RET.T":    {"type": "U16", "index": {None: 0x03FD}, "dp": None, "precision": 0},
               "DISPLAY.TIM.F":    {"type": "U16", "index": {None: 0x0400}, "dp": None, "precision": 0},
               "INPUT.FIL.B":      {"type": "F32", "index": {0: 0x0FAC, 1: 0x0FAE, 2: 0x0FB0, 3: 0x0FB2}, "dp": None, "precision": 0},
               "INPUT.FIL.T":      {"type": "U16", "index": {0: 0x0FB4, 1: 0x0FB5, 2: 0x0FB6, 3: 0x0FB7}, "dp": None, "precision": 0},
               "INPUT.PV":         {"type": "F32", "index": {0: 0x0FA0, 1: 0x0FA2, 2: 0x0FA4, 3: 0x0FA6}, "dp": None, "precision": 0},
               "INPUT.TYPE":       {"type": "U16", "index": {0: 0x0FA8, 1: 0x0FA9, 2: 0x0FAA, 3: 0x0FAB}, "dp": None, "precision": 0},
               "LOGIC.BL.AL":      {"type": "U16", "index": {None: 0xEA63}, "dp": None, "precision": 0},
               "LOGIC.BL.TR":      {"type": "U16", "index": {None: 0xEA64}, "dp": None, "precision": 0},
               "LOGIC.BRK.C":      {"type": "U16", "index": {None: 0xEA6D}, "dp": None, "precision": 0},
               "LOGIC.CTRL":       {"type": "U16", "index": {None: 0xEA60}, "dp": None, "precision": 0},
               "LOGIC.DL.AL":      {"type": "U16", "index": {None: 0xEA61}, "dp": None, "precision": 0},
               "LOGIC.DL.TR":      {"type": "U16", "index": {None: 0xEA62}, "dp": None, "precision": 0},
               "LOGIC.INC":        {"type": "U16", "index": {0: 0xEA65, 1: 0xEA66, 2: 0xEA67, 3: 0xEA68}, "dp": None, "precision": 0},
               "LOGIC.POS":        {"type": "U16", "index": {0: 0xEA69, 1: 0xEA6A, 2: 0xEA6B, 3: 0xEA6C}, "dp": None, "precision": 0},
               "LOGIC.T.FST":      {"type": "U16", "index": {None: 0xEA6E}, "dp": None, "precision": 0},
               "MANUAL.FUN.T":     {"type": "U32", "index": {None: 0xEA7B}, "dp": None, "precision": 0},
               "MANUAL.O.T":       {"type": "U16", "index": {0: 0xEA7D, 1: 0xEA7E, 2: 0xEA7F, 3: 0xEA80}, "dp": None, "precision": 0},
               "SETPOINT.HS.AL":   {"type": "F32", "index": {None: 0xEA77}, "dp": None, "precision": 0},
               "SETPOINT.HS.FN":   {"type": "F32", "index": {None: 0xEA75}, "dp": None, "precision": 0},
               "SETPOINT.HS.TR":   {"type": "F32", "index": {None: 0xEA79}, "dp": None, "precision": 0},
               "SETPOINT.SP.AL":   {"type": "F32", "index": {None: 0xEA71}, "dp": None, "precision": 0},
               "SETPOINT.SP.FN":   {"type": "F32", "index": {None: 0xEA6F}, "dp": None, "precision": 0},
               "SETPOINT.SP.TR":   {"type": "F32", "index": {None: 0xEA73}, "dp": None, "precision": 0},
               "STATISTICS.DEV.T": {"type": "U32", "index": {None: 0xEA97}, "dp": None, "precision": 0},
               "STATISTICS.HI.T":  {"type": "F32", "index": {0: 0xEA8F, 1: 0xEA91, 2: 0xEA93, 3: 0xEA95}, "dp": None, "precision": 0},
               "STATISTICS.O.CN":  {"type": "U16", "index": {0: 0xEA81, 1: 0xEA82, 2: 0xEA83, 3: 0xEA84}, "dp": None, "precision": 0},
               "STATISTICS.O.TM":  {"type": "U32", "index": {0: 0xEA85, 1: 0xEA87, 2: 0xEA89, 3: 0xEA8B}, "dp": None, "precision": 0},
              },
    "byteorder": ">",
    "wordorder": "<",
}
