#! /usr/bin/env python3

"""Таблица настроек модулей МК210."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pymodbus.constants import Endian

if TYPE_CHECKING:
    from owen.device._types import DEVICE

# Модуль дискретного ввода-вывода
MK210_301: DEVICE = {
    "modbus": {"ARCHIVE.LAST":         {"type":    "U16", "index": {None: 0x0387}, "dp": None, "precision": 0},
               "ARCHIVE.PERIOD":       {"type":    "U16", "index": {None: 0x0384}, "dp": None, "precision": 0},
               "ARCHIVE.QUANTITY":     {"type":    "U16", "index": {None: 0x0385}, "dp": None, "precision": 0},
               "ARCHIVE.SIZE":         {"type":    "U16", "index": {None: 0x0386}, "dp": None, "precision": 0},
               "BATTERY.VOLTAGE":      {"type":    "U16", "index": {None: 0x0321}, "dp": None, "precision": 0},
               "CLOUD.ACCESS":         {"type":    "U16", "index": {None: 0x02BF}, "dp": None, "precision": 0},
               "CLOUD.CONNECT":        {"type":    "U16", "index": {None: 0x0023}, "dp": None, "precision": 0},
               "CLOUD.ENABLE":         {"type":    "U16", "index": {None: 0x02BD}, "dp": None, "precision": 0},
               "CLOUD.STATUS":         {"type":    "U16", "index": {None: 0x0024}, "dp": None, "precision": 0},
               "CLOUD.WRITING":        {"type":    "U16", "index": {None: 0x02BE}, "dp": None, "precision": 0},
               "ETHERNET.DHCP":        {"type":    "U16", "index": {None: 0x0020}, "dp": None, "precision": 0},
               "ETHERNET.DNS1":        {"type":    "U32", "index": {None: 0x000C}, "dp": None, "precision": 0},
               "ETHERNET.DNS2":        {"type":    "U32", "index": {None: 0x000E}, "dp": None, "precision": 0},
               "ETHERNET.GATEWAY":     {"type":    "U32", "index": {None: 0x0018}, "dp": None, "precision": 0},
               "ETHERNET.GET_GATEWAY": {"type":    "U32", "index": {None: 0x001E}, "dp": None, "precision": 0},
               "ETHERNET.GET_IP":      {"type":    "U32", "index": {None: 0x001A}, "dp": None, "precision": 0},
               "ETHERNET.GET_MASK":    {"type":    "U32", "index": {None: 0x001C}, "dp": None, "precision": 0},
               "ETHERNET.IP":          {"type":    "U32", "index": {None: 0x0014}, "dp": None, "precision": 0},
               "ETHERNET.MAC":         {"type":    "U32", "index": {None: 0xF100}, "dp": None, "precision": 0},
               "ETHERNET.MASK":        {"type":    "U32", "index": {None: 0x0016}, "dp": None, "precision": 0},
               "MQTT.ADDRESS":         {"type": "STR256", "index": {None: 0x1769}, "dp": None, "precision": 0},
               "MQTT.CONNECT":         {"type":    "U16", "index": {None: 0x1700}, "dp": None, "precision": 0},
               "MQTT.ENABLE":          {"type":    "U16", "index": {None: 0x178A}, "dp": None, "precision": 0},
               "MQTT.INTERVAL":        {"type":    "U16", "index": {None: 0x1704}, "dp": None, "precision": 0},
               "MQTT.KEEPALIVE":       {"type":    "U16", "index": {None: 0x1768}, "dp": None, "precision": 0},
               "MQTT.LOGIN":           {"type": "STR256", "index": {None: 0x1728}, "dp": None, "precision": 0},
               "MQTT.NAME":            {"type": "STR256", "index": {None: 0x1708}, "dp": None, "precision": 0},
               "MQTT.PASSWORD":        {"type": "STR256", "index": {None: 0x1748}, "dp": None, "precision": 0},
               "MQTT.PORT":            {"type":    "U16", "index": {None: 0x1703}, "dp": None, "precision": 0},
               "MQTT.QOS":             {"type":    "U16", "index": {None: 0x1705}, "dp": None, "precision": 0},
               "MQTT.STATUS":          {"type":    "U16", "index": {None: 0x1789}, "dp": None, "precision": 0},
               "MQTT.STORE":           {"type":    "U16", "index": {None: 0x1707}, "dp": None, "precision": 0},
               "NTP.ENABLE":           {"type":    "U16", "index": {None: 0x1600}, "dp": None, "precision": 0},
               "NTP.POOL":             {"type": "STR256", "index": {None: 0x1601}, "dp": None, "precision": 0},
               "NTP.SERVER1":          {"type":    "U32", "index": {None: 0x1641}, "dp": None, "precision": 0},
               "NTP.SERVER2":          {"type":    "U32", "index": {None: 0x1643}, "dp": None, "precision": 0},
               "NTP.STATUS":           {"type":    "U16", "index": {None: 0x1646}, "dp": None, "precision": 0},
               "NTP.TIMINGCYCLE":      {"type":    "U16", "index": {None: 0x1645}, "dp": None, "precision": 0},
               "RTC.MSEC":             {"type":    "U32", "index": {None: 0xF07B}, "dp": None, "precision": 0},
               "RTC.NEWTIME":          {"type":    "U32", "index": {None: 0xF07D}, "dp": None, "precision": 0},
               "RTC.TIMEZONE":         {"type":    "I16", "index": {None: 0xF082}, "dp": None, "precision": 0},
               "RTC.UTC":              {"type":    "U32", "index": {None: 0xF080}, "dp": None, "precision": 0},
               "RTC.WRITE":            {"type":    "U16", "index": {None: 0xF07F}, "dp": None, "precision": 0},
               "SLAVE.TIMEOUT":        {"type":     "U8", "index": {None: 0x02BC}, "dp": None, "precision": 0},
               "SNMP.COMMREAD":        {"type": "STR256", "index": {None: 0x1771}, "dp": None, "precision": 0},
               "SNMP.COMMWRIGHT":      {"type": "STR256", "index": {None: 0x1781}, "dp": None, "precision": 0},
               "SNMP.ENABLE":          {"type":    "U16", "index": {None: 0x1400}, "dp": None, "precision": 0},
               "SNMP.IP":              {"type":    "U32", "index": {None: 0x1401}, "dp": None, "precision": 0},
               "SNMP.PORT":            {"type":    "U16", "index": {None: 0x1403}, "dp": None, "precision": 0},
               "SNMP.VERSION":         {"type":    "U16", "index": {None: 0x1404}, "dp": None, "precision": 0},
               "DEVICE.APPVER":        {"type":  "STR16", "index": {None: 0xF040}, "dp": None, "precision": 0},
               "DEVICE.BOARDNAME":     {"type":  "STR32", "index": {None: 0xF020}, "dp": None, "precision": 0},
               "DEVICE.BOARDVER":      {"type":  "STR32", "index": {None: 0xF030}, "dp": None, "precision": 0},
               "DEVICE.DEV":           {"type":  "STR32", "index": {None: 0xF000}, "dp": None, "precision": 0},
               "DEVICE.INFO":          {"type":  "STR16", "index": {None: 0xF048}, "dp": None, "precision": 0},
               "DEVICE.VER":           {"type":  "STR32", "index": {None: 0xF010}, "dp": None, "precision": 0},
               "DEVICE.NUMBER":        {"type":  "STR32", "index": {None: 0xF084}, "dp": None, "precision": 0},

               "CHANNEL.DI.COUNTER":    {"type": "U32", "index": {0: 0x00A0, 1: 0x00A2, 2: 0x00A4, 3: 0x00A6, 4: 0x00A8, 5: 0x00AA}, "dp": None, "precision": 0},
               "CHANNEL.DI.FILTER":     {"type": "U16", "index": {0: 0x0060, 1: 0x0061, 2: 0x0062, 3: 0x0063, 4: 0x0064, 5: 0x0065}, "dp": None, "precision": 0},
               "CHANNEL.DI.RESET":      {"type": "U16", "index": {0: 0x00E0, 1: 0x00E1, 2: 0x00E2, 3: 0x00E3, 4: 0x00E4, 5: 0x00E5}, "dp": None, "precision": 0},
               "CHANNEL.DO.COEFF":      {"type": "U16", "index": {0: 0x0154, 1: 0x0155, 2: 0x0156, 3: 0x0157, 4: 0x0158, 5: 0x0159, 6: 0x015A, 7: 0x015B}, "dp": None, "precision": 0},
               "CHANNEL.DO.DIAGNOSTIC": {"type": "U16", "index": {0: 0x01B4, 1: 0x01B5, 2: 0x01B6, 3: 0x01B7, 4: 0x01B8, 5: 0x01B9, 6: 0x01BA, 7: 0x01BB}, "dp": None, "precision": 0},
               "CHANNEL.DO.MODE":       {"type": "U16", "index": {0: 0x0110, 1: 0x0111, 2: 0x0112, 3: 0x0113, 4: 0x0114, 5: 0x0115, 6: 0x0116, 7: 0x0117}, "dp": None, "precision": 0},
               "CHANNEL.DO.PERIOD":     {"type": "U16", "index": {0: 0x0134, 1: 0x0135, 2: 0x0136, 3: 0x0137, 4: 0x0138, 5: 0x0139, 6: 0x013A, 7: 0x013B}, "dp": None, "precision": 0},
               "CHANNEL.DO.SAFETY":     {"type": "U16", "index": {0: 0x01DA, 1: 0x01DB, 2: 0x01DC, 3: 0x01DD, 4: 0x01DE, 5: 0x01DF, 6: 0x01E0, 7: 0x01E1}, "dp": None, "precision": 0},
               "DI.STATE":              {"type":  "U8", "index": {None: 0x0033}, "dp": None, "precision": 0},
               "DO.DIAGNOSTIC":         {"type":  "U8", "index": {None: 0x01D8}, "dp": None, "precision": 0},
               "DO.SET_STATE":          {"type":  "U8", "index": {None: 0x01D6}, "dp": None, "precision": 0},
               "DO.STATE":              {"type":  "U8", "index": {None: 0x01D4}, "dp": None, "precision": 0},
              },
    "byteorder": Endian.Big,
    "wordorder": Endian.Little,
}


# Модуль дискретного ввода-вывода
MK210_302: DEVICE = {
    "modbus": {"ARCHIVE.LAST":         {"type":    "U16", "index": {None: 0x0387}, "dp": None, "precision": 0},
               "ARCHIVE.PERIOD":       {"type":    "U16", "index": {None: 0x0384}, "dp": None, "precision": 0},
               "ARCHIVE.QUANTITY":     {"type":    "U16", "index": {None: 0x0385}, "dp": None, "precision": 0},
               "ARCHIVE.SIZE":         {"type":    "U16", "index": {None: 0x0386}, "dp": None, "precision": 0},
               "BATTERY.VOLTAGE":      {"type":    "U16", "index": {None: 0x0321}, "dp": None, "precision": 0},
               "CLOUD.ACCESS":         {"type":    "U16", "index": {None: 0x02BF}, "dp": None, "precision": 0},
               "CLOUD.CONNECT":        {"type":    "U16", "index": {None: 0x0023}, "dp": None, "precision": 0},
               "CLOUD.ENABLE":         {"type":    "U16", "index": {None: 0x02BD}, "dp": None, "precision": 0},
               "CLOUD.STATUS":         {"type":    "U16", "index": {None: 0x0024}, "dp": None, "precision": 0},
               "CLOUD.WRITING":        {"type":    "U16", "index": {None: 0x02BE}, "dp": None, "precision": 0},
               "ETHERNET.DHCP":        {"type":    "U16", "index": {None: 0x0020}, "dp": None, "precision": 0},
               "ETHERNET.DNS1":        {"type":    "U32", "index": {None: 0x000C}, "dp": None, "precision": 0},
               "ETHERNET.DNS2":        {"type":    "U32", "index": {None: 0x000E}, "dp": None, "precision": 0},
               "ETHERNET.GATEWAY":     {"type":    "U32", "index": {None: 0x0018}, "dp": None, "precision": 0},
               "ETHERNET.GET_GATEWAY": {"type":    "U32", "index": {None: 0x001E}, "dp": None, "precision": 0},
               "ETHERNET.GET_IP":      {"type":    "U32", "index": {None: 0x001A}, "dp": None, "precision": 0},
               "ETHERNET.GET_MASK":    {"type":    "U32", "index": {None: 0x001C}, "dp": None, "precision": 0},
               "ETHERNET.IP":          {"type":    "U32", "index": {None: 0x0014}, "dp": None, "precision": 0},
               "ETHERNET.MAC":         {"type":    "U32", "index": {None: 0xF100}, "dp": None, "precision": 0},
               "ETHERNET.MASK":        {"type":    "U32", "index": {None: 0x0016}, "dp": None, "precision": 0},
               "MQTT.ADDRESS":         {"type": "STR256", "index": {None: 0x1769}, "dp": None, "precision": 0},
               "MQTT.CONNECT":         {"type":    "U16", "index": {None: 0x1700}, "dp": None, "precision": 0},
               "MQTT.ENABLE":          {"type":    "U16", "index": {None: 0x178A}, "dp": None, "precision": 0},
               "MQTT.INTERVAL":        {"type":    "U16", "index": {None: 0x1704}, "dp": None, "precision": 0},
               "MQTT.KEEPALIVE":       {"type":    "U16", "index": {None: 0x1768}, "dp": None, "precision": 0},
               "MQTT.LOGIN":           {"type": "STR256", "index": {None: 0x1728}, "dp": None, "precision": 0},
               "MQTT.NAME":            {"type": "STR256", "index": {None: 0x1708}, "dp": None, "precision": 0},
               "MQTT.PASSWORD":        {"type": "STR256", "index": {None: 0x1748}, "dp": None, "precision": 0},
               "MQTT.PORT":            {"type":    "U16", "index": {None: 0x1703}, "dp": None, "precision": 0},
               "MQTT.QOS":             {"type":    "U16", "index": {None: 0x1705}, "dp": None, "precision": 0},
               "MQTT.STATUS":          {"type":    "U16", "index": {None: 0x1789}, "dp": None, "precision": 0},
               "MQTT.STORE":           {"type":    "U16", "index": {None: 0x1707}, "dp": None, "precision": 0},
               "NTP.ENABLE":           {"type":    "U16", "index": {None: 0x1600}, "dp": None, "precision": 0},
               "NTP.POOL":             {"type": "STR256", "index": {None: 0x1601}, "dp": None, "precision": 0},
               "NTP.SERVER1":          {"type":    "U32", "index": {None: 0x1641}, "dp": None, "precision": 0},
               "NTP.SERVER2":          {"type":    "U32", "index": {None: 0x1643}, "dp": None, "precision": 0},
               "NTP.STATUS":           {"type":    "U16", "index": {None: 0x1646}, "dp": None, "precision": 0},
               "NTP.TIMINGCYCLE":      {"type":    "U16", "index": {None: 0x1645}, "dp": None, "precision": 0},
               "RTC.MSEC":             {"type":    "U32", "index": {None: 0xF07B}, "dp": None, "precision": 0},
               "RTC.NEWTIME":          {"type":    "U32", "index": {None: 0xF07D}, "dp": None, "precision": 0},
               "RTC.TIMEZONE":         {"type":    "I16", "index": {None: 0xF082}, "dp": None, "precision": 0},
               "RTC.UTC":              {"type":    "U32", "index": {None: 0xF080}, "dp": None, "precision": 0},
               "RTC.WRITE":            {"type":    "U16", "index": {None: 0xF07F}, "dp": None, "precision": 0},
               "SLAVE.TIMEOUT":        {"type":     "U8", "index": {None: 0x02BC}, "dp": None, "precision": 0},
               "SNMP.COMMREAD":        {"type": "STR256", "index": {None: 0x1771}, "dp": None, "precision": 0},
               "SNMP.COMMWRIGHT":      {"type": "STR256", "index": {None: 0x1781}, "dp": None, "precision": 0},
               "SNMP.ENABLE":          {"type":    "U16", "index": {None: 0x1400}, "dp": None, "precision": 0},
               "SNMP.IP":              {"type":    "U32", "index": {None: 0x1401}, "dp": None, "precision": 0},
               "SNMP.PORT":            {"type":    "U16", "index": {None: 0x1403}, "dp": None, "precision": 0},
               "SNMP.VERSION":         {"type":    "U16", "index": {None: 0x1404}, "dp": None, "precision": 0},
               "DEVICE.APPVER":        {"type":  "STR16", "index": {None: 0xF040}, "dp": None, "precision": 0},
               "DEVICE.BOARDNAME":     {"type":  "STR32", "index": {None: 0xF020}, "dp": None, "precision": 0},
               "DEVICE.BOARDVER":      {"type":  "STR32", "index": {None: 0xF030}, "dp": None, "precision": 0},
               "DEVICE.DEV":           {"type":  "STR32", "index": {None: 0xF000}, "dp": None, "precision": 0},
               "DEVICE.INFO":          {"type":  "STR16", "index": {None: 0xF048}, "dp": None, "precision": 0},
               "DEVICE.VER":           {"type":  "STR32", "index": {None: 0xF010}, "dp": None, "precision": 0},
               "DEVICE.NUMBER":        {"type":  "STR32", "index": {None: 0xF084}, "dp": None, "precision": 0},

               "CHANNEL.DI.MODE":       {"type": "U16", "index": {0: 0x0040, 1: 0x0041, 2: 0x0042, 3: 0x0043, 4: 0x0044, 5: 0x0045, 6: 0x0046, 7: 0x0047}, "dp": None, "precision": 0},
               "CHANNEL.DI.PERIOD":     {"type": "U16", "index": {0: 0x0080, 1: 0x0081, 2: 0x0082, 3: 0x0083, 4: 0x0084, 5: 0x0085, 6: 0x0086, 7: 0x0087}, "dp": None, "precision": 0},
               "CHANNEL.DI.FILTER":     {"type": "U16", "index": {0: 0x0060, 1: 0x0061, 2: 0x0062, 3: 0x0063, 4: 0x0064, 5: 0x0065, 6: 0x0066, 7: 0x0067, 8: 0x0068, 9: 0x0069, 10: 0x006A, 11: 0x006B}, "dp": None, "precision": 0},
               "CHANNEL.DI.COUNTER":    {"type": "U32", "index": {0: 0x00A0, 1: 0x00A2, 2: 0x00A4, 3: 0x00A6, 4: 0x00A8, 5: 0x00AA, 6: 0x00AC, 7: 0x00AE, 8: 0x00B0, 9: 0x00B2, 10: 0x00B4, 11: 0x00B6}, "dp": None, "precision": 0},
               "CHANNEL.DI.RESET":      {"type": "U16", "index": {0: 0x00E0, 1: 0x00E1, 2: 0x00E2, 3: 0x00E3, 4: 0x00E4, 5: 0x00E5, 6: 0x00E6, 7: 0x00E7, 8: 0x00E8, 9: 0x00E9, 10: 0x00EA, 11: 0x00EB}, "dp": None, "precision": 0},
               "CHANNEL.DO.MODE":       {"type": "U16", "index": {0: 0x0110, 1: 0x0111, 2: 0x0112, 3: 0x0113}, "dp": None, "precision": 0},
               "CHANNEL.DO.PERIOD":     {"type": "U16", "index": {0: 0x0134, 1: 0x0135, 2: 0x0136, 3: 0x0137}, "dp": None, "precision": 0},
               "CHANNEL.DO.COEFF":      {"type": "U16", "index": {0: 0x0154, 1: 0x0155, 2: 0x0156, 3: 0x0157}, "dp": None, "precision": 0},
               "CHANNEL.DO.DIAGNOSTIC": {"type": "U16", "index": {0: 0x01B4, 1: 0x01B5, 2: 0x01B6, 3: 0x01B7}, "dp": None, "precision": 0},
               "CHANNEL.DO.SAFETY":     {"type": "U16", "index": {0: 0x01DA, 1: 0x01DB, 2: 0x01DC, 3: 0x01DD}, "dp": None, "precision": 0},
               "DO.STATE":              {"type":  "U8", "index": {None: 0x01D4}, "dp": None, "precision": 0},
               "DO.SET_STATE":          {"type":  "U8", "index": {None: 0x01D6}, "dp": None, "precision": 0},
               "DO.DIAGNOSTIC":         {"type":  "U8", "index": {None: 0x01D8}, "dp": None, "precision": 0},
               "DI.STATE":              {"type":  "U8", "index": {None: 0x0033}, "dp": None, "precision": 0},
              },
    "byteorder": Endian.Big,
    "wordorder": Endian.Little,
}
