#! /usr/bin/env python3

"""Таблица настроек счетчика импульсов СИ130."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from owen.device._types import DEVICE

SI130: DEVICE = {
    "modbus": {"ARCHIVE.LAST":         {"type":    "U32", "index": {None: 0x038E}, "dp": None, "precision": 0},
               "ARCHIVE.PERIOD":       {"type":    "U16", "index": {None: 0x0384}, "dp": None, "precision": 0},
               "ARCHIVE.QUANTITY":     {"type":    "U32", "index": {None: 0x0385}, "dp": None, "precision": 0},
               "ARCHIVE.SIZE":         {"type":    "U32", "index": {None: 0x038C}, "dp": None, "precision": 0},
               "BATTERY.STATE":        {"type":     "U8", "index": {None: 0x0322}, "dp": None, "precision": 0},
               "BATTERY.THRESHOLD":    {"type":    "U16", "index": {None: 0x0320}, "dp": None, "precision": 0},
               "BATTERY.VOLTAGE":      {"type":    "U16", "index": {None: 0x0321}, "dp": None, "precision": 0},
               "CLOUD.ACCESS":         {"type":     "U8", "index": {None: 0x02BF}, "dp": None, "precision": 0},
               "CLOUD.ENABLE":         {"type":     "U8", "index": {None: 0x02BD}, "dp": None, "precision": 0},
               "CLOUD.WRITING":        {"type":     "U8", "index": {None: 0x02BE}, "dp": None, "precision": 0},
               "DATATIME.DAYS":        {"type":     "U8", "index": {None: 0xF078}, "dp": None, "precision": 0},
               "DATATIME.HOURS":       {"type":     "U8", "index": {None: 0xF077}, "dp": None, "precision": 0},
               "DATATIME.MINUTES":     {"type":     "U8", "index": {None: 0xF076}, "dp": None, "precision": 0},
               "DATATIME.MONTHS":      {"type":     "U8", "index": {None: 0xF079}, "dp": None, "precision": 0},
               "DATATIME.SECONDS":     {"type":     "U8", "index": {None: 0xF075}, "dp": None, "precision": 0},
               "DATATIME.WEEKDAY":     {"type":     "U8", "index": {None: 0xF074}, "dp": None, "precision": 0},
               "DATATIME.YEARS":       {"type":    "U16", "index": {None: 0xF07A}, "dp": None, "precision": 0},
               "DISPLAY.CHANGER":      {"type":     "U8", "index": {None: 0x0404}, "dp": None, "precision": 0},
               "DISPLAY.DOWNTIME":     {"type":     "U8", "index": {None: 0x0402}, "dp": None, "precision": 0},
               "DISPLAY.MODE":         {"type":     "U8", "index": {None: 0x0406}, "dp": None, "precision": 0},
               "DISPLAY.NUMBER":       {"type":     "U8", "index": {0: 0x03FC, 1: 0x03FE, 2: 0x0400}, "dp": None, "precision": 0},
               "ETHERNET.APPLY":       {"type":     "U8", "index": {None: 0x0021}, "dp": None, "precision": 0},
               "ETHERNET.DHCP":        {"type":     "U8", "index": {None: 0x0020}, "dp": None, "precision": 0},
               "ETHERNET.GATEWAY":     {"type":    "U32", "index": {None: 0x0018}, "dp": None, "precision": 0},
               "ETHERNET.GET_GATEWAY": {"type":    "U32", "index": {None: 0x001E}, "dp": None, "precision": 0},
               "ETHERNET.GET_IP":      {"type":    "U32", "index": {None: 0x001A}, "dp": None, "precision": 0},
               "ETHERNET.GET_MASK":    {"type":    "U32", "index": {None: 0x001C}, "dp": None, "precision": 0},
               "ETHERNET.IP":          {"type":    "U32", "index": {None: 0x0014}, "dp": None, "precision": 0},
               "ETHERNET.MAC":         {"type":    "U32", "index": {None: 0xF110}, "dp": None, "precision": 0},
               "ETHERNET.MASK":        {"type":    "U32", "index": {None: 0x0016}, "dp": None, "precision": 0},
               "ETHERNET.STATUS":      {"type":     "U8", "index": {None: 0x0022}, "dp": None, "precision": 0},
               "RS485.BAUDRATE":       {"type":     "U8", "index": {None: 0x02EE}, "dp": None, "precision": 0},
               "RS485.DATABITS":       {"type":     "U8", "index": {None: 0x02EF}, "dp": None, "precision": 0},
               "RS485.PARITY":         {"type":     "U8", "index": {None: 0x02F0}, "dp": None, "precision": 0},
               "RS485.SLAVEID":        {"type":     "U8", "index": {None: 0x02F2}, "dp": None, "precision": 0},
               "RS485.STOPBITS":       {"type":     "U8", "index": {None: 0x02F1}, "dp": None, "precision": 0},
               "RTC.MSEC":             {"type":    "U32", "index": {None: 0xF07B}, "dp": None, "precision": 0},
               "RTC.TIMEZONE":         {"type":    "U16", "index": {None: 0xF073}, "dp": None, "precision": 0},
               "RTC.UTC":              {"type":    "U32", "index": {None: 0xF071}, "dp": None, "precision": 0},
               "SLAVE.TIMEOUT":        {"type":     "U8", "index": {None: 0x02BC}, "dp": None, "precision": 0},
               "USB.FOLDER":           {"type": "STR128", "index": {None: 0xEA57}, "dp": None, "precision": 0},
               "USB.PERCENT":          {"type":     "U8", "index": {None: 0xEA5F}, "dp": None, "precision": 0},
               "USB.STATUS":           {"type":     "U8", "index": {None: 0xEA56}, "dp": None, "precision": 0},
               "DEVICE.APPVER":        {"type":  "STR16", "index": {None: 0xF040}, "dp": None, "precision": 0},
               "DEVICE.BOARDNAME":     {"type":  "STR32", "index": {None: 0xF020}, "dp": None, "precision": 0},
               "DEVICE.BOARDVER":      {"type":  "STR32", "index": {None: 0xF030}, "dp": None, "precision": 0},
               "DEVICE.DEV":           {"type":  "STR32", "index": {None: 0xF000}, "dp": None, "precision": 0},
               "DEVICE.INFO":          {"type":  "STR16", "index": {None: 0xF048}, "dp": None, "precision": 0},
               "DEVICE.VER":           {"type":  "STR32", "index": {None: 0xF010}, "dp": None, "precision": 0},
               "DEVICE.NUMBER":        {"type":  "STR32", "index": {None: 0xF084}, "dp": None, "precision": 0},
               "DEVICE.TIMEZONE":      {"type":    "I16", "index": {None: 0xF082}, "dp": None, "precision": 0},

               "UNIT.TYPE":             {"type":    "U8", "index": {0: 0xEA78, 1: 0xEA8A}, "dp": None, "precision": 0},
               "UNIT.MULTIPLIER":       {"type":   "F32", "index": {0: 0xEA79, 1: 0xEA8B}, "dp": None, "precision": 0},
               "UNIT.PV":               {"type":   "F32", "index": {0: 0xEA62, 1: 0xEA6B}, "dp": None, "precision": 0},
               "UNIT.DP":               {"type":    "U8", "index": {0: 0xEA7B, 1: 0xEA8D}, "dp": None, "precision": 0},
               "UNIT.SPMODE":           {"type":    "U8", "index": {0: 0xEA7C, 1: 0xEA8E}, "dp": None, "precision": 0},
               "UNIT.RESETMODE":        {"type":    "U8", "index": {0: 0xEA7D, 1: 0xEA8F}, "dp": None, "precision": 0},
               "UNIT.RESETBLOCK":       {"type":    "U8", "index": {0: 0xEA7E, 1: 0xEA90}, "dp": None, "precision": 0},
               "UNIT.INPUT1":           {"type":    "U8", "index": {0: 0xEA7F, 1: 0xEA91}, "dp": None, "precision": 0},
               "UNIT.INPUT2":           {"type":    "U8", "index": {0: 0xEA80, 1: 0xEA92}, "dp": None, "precision": 0},
               "UNIT.INPUT3":           {"type":    "U8", "index": {0: 0xEA81, 1: 0xEA93}, "dp": None, "precision": 0},
               "UNIT.INPUT4":           {"type":    "U8", "index": {0: 0xEA82, 1: 0xEA94}, "dp": None, "precision": 0},
               "UNIT.INPUT5":           {"type":    "U8", "index": {0: 0xEA83, 1: 0xEA95}, "dp": None, "precision": 0},
               "UNIT.STATE":            {"type":    "U8", "index": {0: 0xEA64, 1: 0xEA6D}, "dp": None, "precision": 0},
               "UNIT.MASK":             {"type":   "U16", "index": {0: 0xEA65, 1: 0xEA6E}, "dp": None, "precision": 0},
               "UNIT.RESET":            {"type":    "U8", "index": {0: 0xEACF, 1: 0xEAD0}, "dp": None, "precision": 0},
               "UNIT.ENCODER.MODE":     {"type":    "U8", "index": {0: 0xEA72, 1: 0xEA84}, "dp": None, "precision": 0},
               "UNIT.ENCODER.INITIAL":  {"type":   "I32", "index": {0: 0xEA73, 1: 0xEA85}, "dp": None, "precision": 0},
               "UNIT.TACHOMETER.SCALE": {"type":    "U8", "index": {0: 0xEA75, 1: 0xEA87}, "dp": None, "precision": 0},
               "UNIT.COUNTER.SCALE":    {"type":    "U8", "index": {0: 0xEA76, 1: 0xEA88}, "dp": None, "precision": 0},
               "UNIT.COUNTER.ACTION":   {"type":   "U32", "index": {0: 0xEA60, 1: 0xEA69}, "dp": None, "precision": 0},
               "UNIT.COUNTER.START":    {"type":    "U8", "index": {0: 0xEA77, 1: 0xEA89}, "dp": None, "precision": 0},

               "INPUT.LEVEL":           {"type":    "U8", "index": {0: 0xEA96, 1: 0xEA9B, 2: 0xEAA0, 3: 0xEAA5, 4: 0xEAAA}, "dp": None, "precision": 0},
               "INPUT.DURATION":        {"type":   "U32", "index": {0: 0xEA97, 1: 0xEA9C, 2: 0xEAA1, 3: 0xEAA6, 4: 0xEAAB}, "dp": None, "precision": 0},
               "INPUT.INTERVAL":        {"type":   "U32", "index": {0: 0xEA99, 1: 0xEA9E, 2: 0xEAA3, 3: 0xEAA8, 4: 0xEAAD}, "dp": None, "precision": 0},

               "OUTPUT.SETPOINT_S":     {"type":   "F32", "index": {0: 0xEAAF, 1: 0xEABF}, "dp": None, "precision": 0},
               "OUTPUT.SETPOINT_H":     {"type":   "U32", "index": {0: 0xEAB1, 1: 0xEAC1}, "dp": None, "precision": 0},
               "OUTPUT.DEFAULT":        {"type":    "U8", "index": {0: 0xEABE, 1: 0xEACE}, "dp": None, "precision": 0},
               "OUTPUT.TYPE":           {"type":    "U8", "index": {0: 0xEA66, 1: 0xEA6F}, "dp": None, "precision": 0},
               "OUTPUT.VALUE":          {"type":   "F32", "index": {0: 0xEA67, 1: 0xEA70}, "dp": None, "precision": 0},
               "OUTPUT.ANALOG.MODE":    {"type":    "U8", "index": {0: 0xEAB3, 1: 0xEAC3}, "dp": None, "precision": 0},
               "OUTPUT.ANALOG.LOW":     {"type":   "F32", "index": {0: 0xEAB4, 1: 0xEAC4}, "dp": None, "precision": 0},
               "OUTPUT.ANALOG.HIGH":    {"type":   "F32", "index": {0: 0xEAB6, 1: 0xEAC6}, "dp": None, "precision": 0},
               "OUTPUT.ANALOG.DELTA":   {"type":   "F32", "index": {0: 0xEAB8, 1: 0xEAC8}, "dp": None, "precision": 0},
               "OUTPUT.DISCRET.HYST":   {"type":   "U32", "index": {0: 0xEABA, 1: 0xEB52}, "dp": None, "precision": 0},
               "OUTPUT.DISCRET.MODE":   {"type":    "U8", "index": {0: 0xEABC, 1: 0xEB54}, "dp": None, "precision": 0},
               "OUTPUT.DISCRET.HOLD":   {"type":   "U16", "index": {0: 0xEABD, 1: 0xEB56}, "dp": None, "precision": 0},
              },
    "byteorder": ">",
    "wordorder": "<",
}
