#! /usr/bin/env python3

"""Таблица настроек измерителя-ПИД-регулятора ТРМ210."""

from __future__ import annotations

from typing import TYPE_CHECKING

from pymodbus.constants import Endian

if TYPE_CHECKING:
    from owen.device._types import DEVICE

TRM210: DEVICE = {
    "owen": {"PV":    {"type": "F24", "index": {None: None}},
             "SP":    {"type": "F24", "index": {None: None}},
             "R-S":   {"type":  "U8", "index": {None: None}},
             "AT":    {"type":  "U8", "index": {None: None}},
             "O":     {"type": "F24", "index": {None: None}},
             "IN-T":  {"type":  "U8", "index": {None: None}},
             "DPT":   {"type":  "U8", "index": {None: None}},
             "DP":    {"type":  "U8", "index": {None: None}},
             "IN-L":  {"type": "F24", "index": {None: None}},
             "IN-H":  {"type": "F24", "index": {None: None}},
             "SL-L":  {"type": "F24", "index": {None: None}},
             "SL-H":  {"type": "F24", "index": {None: None}},
             "SH":    {"type": "F24", "index": {None: None}},
             "KU":    {"type": "F24", "index": {None: None}},
             "INF":   {"type": "F24", "index": {None: None}},
             "FB":    {"type": "F24", "index": {None: None}},
             "AN-L":  {"type": "F24", "index": {None: None}},
             "AN-H":  {"type": "F24", "index": {None: None}},
             "EV-1":  {"type":  "U8", "index": {None: None}},
             "ALT":   {"type":  "U8", "index": {None: None}},
             "AL-D":  {"type": "F24", "index": {None: None}},
             "AL-H":  {"type": "F24", "index": {None: None}},
             "OREU":  {"type":  "U8", "index": {None: None}},
             "CP":    {"type":  "U8", "index": {None: None}},
             "VSP":   {"type": "F24", "index": {None: None}},
             "CNTL":  {"type":  "U8", "index": {None: None}},
             "HYST":  {"type": "F24", "index": {None: None}},
             "ONST":  {"type":  "U8", "index": {None: None}},
             "ONER":  {"type":  "U8", "index": {None: None}},
             "RAMP":  {"type":  "U8", "index": {None: None}},
             "P":     {"type": "F24", "index": {None: None}},
             "I":     {"type": "F24", "index": {None: None}},
             "D":     {"type": "F24", "index": {None: None}},
             "DB":    {"type": "F24", "index": {None: None}},
             "OL-L":  {"type": "F24", "index": {None: None}},
             "OL-H":  {"type": "F24", "index": {None: None}},
             "ORL":   {"type": "F24", "index": {None: None}},
             "MVER":  {"type": "F24", "index": {None: None}},
             "MVST":  {"type": "F24", "index": {None: None}},
             "MDST":  {"type":  "U8", "index": {None: None}},
             "LBA":   {"type": "U16", "index": {None: None}},
             "LBAB":  {"type": "F24", "index": {None: None}},
             "PROT":  {"type":  "U8", "index": {None: None}},
             "ADDR":  {"type": "U16", "index": {None: None}},
             "RSDL":  {"type":  "U8", "index": {None: None}},
             "A.LEN": {"type":  "U8", "index": {None: None}},
             "BPS":   {"type":  "U8", "index": {None: None}},
             "LEN":   {"type":  "U8", "index": {None: None}},
             "PRTY":  {"type":  "U8", "index": {None: None}},
             "SBIT":  {"type":  "U8", "index": {None: None}},
             "VER":   {"type": "STR", "index": {None: None}},
             "DEV":   {"type": "STR", "index": {None: None}},
             "PRTL":  {"type":  "U8", "index": {None: None}},
             "APLY":  {"type":  "U8", "index": {None: None}},
             "INIT":  {"type":  "U8", "index": {None: None}},
             "N.ERR": {"type": "U24", "index": {None: None}},
             "ATTR":  {"type":  "U8", "index": {None: None}},
             "R-L":   {"type":  "U8", "index": {None: None}},
             "R.OUT": {"type": "F24", "index": {None: None}},
             "EDPT":  {"type":  "U8", "index": {None: None}},
            },
    "modbus": {"STAT":  {"type":  "U16", "index": {None: 0x0000}, "dp": None, "precision": 0},
               "PV":    {"type":  "F32", "index": {None: 0x1009}, "dp": None, "precision": 0},
               "SP":    {"type":  "I16", "index": {None: 0x0002}, "dp": "DP", "precision": 0},
               "SET.P": {"type":  "F32", "index": {None: 0x100D}, "dp": None, "precision": 0},
               "O":     {"type":  "F32", "index": {None: 0x100F}, "dp": None, "precision": 0},
               "R-L":   {"type":  "U16", "index": {None: 0x0005}, "dp": None, "precision": 0},
               "R.OUT": {"type":  "U16", "index": {None: 0x0006}, "dp": None, "precision": 3},
               "R-S":   {"type":  "U16", "index": {None: 0x0007}, "dp": None, "precision": 0},
               "AT":    {"type":  "U16", "index": {None: 0x0008}, "dp": None, "precision": 0},
               "DEV":   {"type": "STR8", "index": {None: 0x1000}, "dp": None, "precision": 0},
               "VER":   {"type": "STR8", "index": {None: 0x1004}, "dp": None, "precision": 0},
               "PROT":  {"type":  "U16", "index": {None: 0x0100}, "dp": None, "precision": 0},
               "BPS":   {"type":  "U16", "index": {None: 0x0101}, "dp": None, "precision": 0},
               "A.LEN": {"type":  "U16", "index": {None: 0x0102}, "dp": None, "precision": 0},
               "ADDR":  {"type":  "U16", "index": {None: 0x0103}, "dp": None, "precision": 0},
               "RSDL":  {"type":  "U16", "index": {None: 0x0104}, "dp": None, "precision": 0},
               "LEN":   {"type":  "U16", "index": {None: 0x0105}, "dp": None, "precision": 0},
               "PRTY":  {"type":  "U16", "index": {None: 0x0106}, "dp": None, "precision": 0},
               "SBIT":  {"type":  "U16", "index": {None: 0x0107}, "dp": None, "precision": 0},
               "N.ERR": {"type":  "U16", "index": {None: 0x0108}, "dp": None, "precision": 0},
               "PRTL":  {"type":  "U16", "index": {None: 0x0109}, "dp": None, "precision": 0},
               "APLY":  {"type":  "U16", "index": {None: 0x010A}, "dp": None, "precision": 0},
               "INIT":  {"type":  "U16", "index": {None: 0x010B}, "dp": None, "precision": 0},
               "IN-T":  {"type":  "U16", "index": {None: 0x0200}, "dp": None, "precision": 0},
               "DPT":   {"type":  "U16", "index": {None: 0x0201}, "dp": None, "precision": 0},
               "DP":    {"type":  "U16", "index": {None: 0x0202}, "dp": None, "precision": 0},
               "IN-L":  {"type":  "I16", "index": {None: 0x0203}, "dp": "DP", "precision": 0},
               "IN-H":  {"type":  "I16", "index": {None: 0x0204}, "dp": "DP", "precision": 0},
               "SH":    {"type":  "I16", "index": {None: 0x0205}, "dp": "DP", "precision": 0},
               "KU":    {"type":  "U16", "index": {None: 0x0206}, "dp": None, "precision": 3},
               "FB":    {"type":  "U16", "index": {None: 0x0207}, "dp": "DP", "precision": 0},
               "INF":   {"type":  "U16", "index": {None: 0x0208}, "dp": None, "precision": 0},
               "SL-L":  {"type":  "I16", "index": {None: 0x0300}, "dp": "DP", "precision": 0},
               "SL-H":  {"type":  "I16", "index": {None: 0x0301}, "dp": "DP", "precision": 0},
               "OREU":  {"type":  "U16", "index": {None: 0x0302}, "dp": None, "precision": 0},
               "CNTL":  {"type":  "U16", "index": {None: 0x0303}, "dp": None, "precision": 0},
               "CP":    {"type":  "U16", "index": {None: 0x0304}, "dp": None, "precision": 0},
               "RAMP":  {"type":  "U16", "index": {None: 0x0305}, "dp": None, "precision": 0},
               "P":     {"type":  "U16", "index": {None: 0x0306}, "dp": "DP", "precision": 0},
               "I":     {"type":  "U16", "index": {None: 0x0307}, "dp": None, "precision": 0},
               "D":     {"type":  "U16", "index": {None: 0x0308}, "dp": None, "precision": 0},
               "DB":    {"type":  "U16", "index": {None: 0x0309}, "dp": "DP", "precision": 0},
               "VSP":   {"type":  "U16", "index": {None: 0x030A}, "dp": "DP", "precision": 0},
               "OL-L":  {"type":  "U16", "index": {None: 0x030B}, "dp": None, "precision": 0},
               "OL-H":  {"type":  "U16", "index": {None: 0x030C}, "dp": None, "precision": 0},
               "ORL":   {"type":  "U16", "index": {None: 0x030D}, "dp": None, "precision": 1},
               "MVER":  {"type":  "U16", "index": {None: 0x030E}, "dp": None, "precision": 0},
               "MDST":  {"type":  "U16", "index": {None: 0x030F}, "dp": None, "precision": 0},
               "MVST":  {"type":  "U16", "index": {None: 0x0310}, "dp": None, "precision": 0},
               "HYST":  {"type":  "U16", "index": {None: 0x0311}, "dp": "DP", "precision": 0},
               "ONST":  {"type":  "U16", "index": {None: 0x0312}, "dp": None, "precision": 0},
               "ONER":  {"type":  "U16", "index": {None: 0x0313}, "dp": None, "precision": 0},
               "EV-1":  {"type":  "U16", "index": {None: 0x0400}, "dp": None, "precision": 0},
               "LBA":   {"type":  "U16", "index": {None: 0x0401}, "dp": None, "precision": 0},
               "LBAB":  {"type":  "U16", "index": {None: 0x0402}, "dp": "DP", "precision": 0},
               "ALT":   {"type":  "U16", "index": {None: 0x0403}, "dp": None, "precision": 0},
               "AL-D":  {"type":  "U16", "index": {None: 0x0404}, "dp": "DP", "precision": 0},
               "AL-H":  {"type":  "U16", "index": {None: 0x0405}, "dp": "DP", "precision": 0},
               "AN-L":  {"type":  "I16", "index": {None: 0x0406}, "dp": "DP", "precision": 0},
               "AN-H":  {"type":  "I16", "index": {None: 0x0407}, "dp": "DP", "precision": 0},
              },
    "byteorder": Endian.Big,
    "wordorder": Endian.Big,
}
