#! /usr/bin/env python3

"""Таблица настроек измерителя-ПИД-регулятора ТРМ212."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from owen.device._types import DEVICE

TRM212: DEVICE = {
    "owen": {"PV":    {"type": "F24", "index": {None: None}},
             "LUPV":  {"type": "F24", "index": {None: None}},
             "SP":    {"type": "F24", "index": {None: None}},
             "SET.P": {"type": "F24", "index": {None: None}},
             "R-S":   {"type":  "U8", "index": {None: None}},
             "AT":    {"type":  "U8", "index": {None: None}},
             "O":     {"type": "F24", "index": {None: None}},
             "IN.T":  {"type":  "U8", "index": {0: 0, 1: 1}},
             "DPT":   {"type":  "U8", "index": {0: 0, 1: 1}},
             "DP":    {"type":  "U8", "index": {0: 0, 1: 1}},
             "IN.L":  {"type": "F24", "index": {0: 0, 1: 1}},
             "IN.H":  {"type": "F24", "index": {0: 0, 1: 1}},
             "SQR":   {"type":  "U8", "index": {0: 0, 1: 1}},
             "SH":    {"type": "F24", "index": {0: 0, 1: 1}},
             "KU":    {"type": "F24", "index": {0: 0, 1: 1}},
             "FB":    {"type": "F24", "index": {0: 0, 1: 1}},
             "INF":   {"type": "F24", "index": {0: 0, 1: 1}},
             "INP2":  {"type":  "U8", "index": {None: None}},
             "CALC":  {"type":  "U8", "index": {None: None}},
             "KPV1":  {"type": "F24", "index": {None: None}},
             "KPV2":  {"type": "F24", "index": {None: None}},
             "SL-L":  {"type": "F24", "index": {None: None}},
             "SL-H":  {"type": "F24", "index": {None: None}},
             "OREU":  {"type":  "U8", "index": {None: None}},
             "RAMP":  {"type":  "U8", "index": {None: None}},
             "PV0":   {"type": "F24", "index": {None: None}},
             "P":     {"type": "F24", "index": {None: None}},
             "I":     {"type": "F24", "index": {None: None}},
             "D":     {"type": "F24", "index": {None: None}},
             "KA":    {"type": "F24", "index": {None: None}},
             "DB":    {"type": "F24", "index": {None: None}},
             "VSP":   {"type": "F24", "index": {None: None}},
             "OL-L":  {"type": "F24", "index": {None: None}},
             "OL-H":  {"type": "F24", "index": {None: None}},
             "MVER":  {"type": "F24", "index": {None: None}},
             "MVST":  {"type": "F24", "index": {None: None}},
             "MDST":  {"type":  "U8", "index": {None: None}},
             "LBA":   {"type": "U16", "index": {None: None}},
             "LBAB":  {"type": "F24", "index": {None: None}},
             "ALT":   {"type":  "U8", "index": {None: None}},
             "AL-D":  {"type": "F24", "index": {None: None}},
             "AL-H":  {"type": "F24", "index": {None: None}},
             "V.MOT": {"type": "F24", "index": {None: None}},
             "V.DB":  {"type": "F24", "index": {None: None}},
             "V.GAP": {"type": "F24", "index": {None: None}},
             "V.REV": {"type": "F24", "index": {None: None}},
             "V.TOF": {"type":  "U8", "index": {None: None}},
             "DIS1":  {"type":  "U8", "index": {None: None}},
             "DIS2":  {"type":  "U8", "index": {None: None}},
             "DIS3":  {"type":  "U8", "index": {None: None}},
             "DIS4":  {"type":  "U8", "index": {None: None}},
             "DIS5":  {"type":  "U8", "index": {None: None}},
             "RET":   {"type":  "U8", "index": {None: None}},
             "NODE":  {"type":  "U8", "index": {None: None}},
             "X":     {"type": "F24", "index": {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10}},
             "Y":     {"type": "F24", "index": {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10}},
             "PROT":  {"type":  "U8", "index": {None: None}},
             "BPS":   {"type":  "U8", "index": {None: None}},
             "A.LEN": {"type":  "U8", "index": {None: None}},
             "ADDR":  {"type": "U16", "index": {None: None}},
             "RSDL":  {"type":  "U8", "index": {None: None}},
             "LEN":   {"type":  "U8", "index": {None: None}},
             "PRTY":  {"type":  "U8", "index": {None: None}},
             "SBIT":  {"type":  "U8", "index": {None: None}},
             "VER":   {"type": "STR", "index": {None: None}},
             "DEV":   {"type": "STR", "index": {None: None}},
             "PRTL":  {"type":  "U8", "index": {None: None}},
             "APLY":  {"type":  "U8", "index": {None: None}},
             "INIT":  {"type":  "U8", "index": {None: None}},
             "N.ERR": {"type": "U24", "index": {None: None}},
             "ATTR":  {"type":  "U8", "index": {None: None}},
             "R-L":   {"type":  "U8", "index": {None: None}},
             "R.OUT": {"type": "F24", "index": {None: None}},
             "OAPT":  {"type":  "U8", "index": {None: None}},
             "WTPT":  {"type":  "U8", "index": {None: None}},
             "EDPT":  {"type":  "U8", "index": {None: None}},
            },
    "modbus": {"STAT":  {"type":  "U16", "index": {None: 0x0000}, "dp": None, "precision": 0},
               "LUPV":  {"type":  "F32", "index": {None: 0x100D}, "dp": None, "precision": 0},
               "SP":    {"type":  "I16", "index": {None: 0x0004}, "dp": "DP", "precision": 0},
               "SET.P": {"type":  "F32", "index": {None: 0x1011}, "dp": None, "precision": 0},
               "O":     {"type":  "F32", "index": {None: 0x1013}, "dp": None, "precision": 0},
               "R-L":   {"type":  "U16", "index": {None: 0x0007}, "dp": None, "precision": 0},
               "R.OUT": {"type":  "U16", "index": {None: 0x0008}, "dp": None, "precision": 3},
               "R-S":   {"type":  "U16", "index": {None: 0x0009}, "dp": None, "precision": 0},
               "AT":    {"type":  "U16", "index": {None: 0x000A}, "dp": None, "precision": 0},
               "DEV":   {"type": "STR8", "index": {None: 0x1000}, "dp": None, "precision": 0},
               "VER":   {"type": "STR8", "index": {None: 0x1004}, "dp": None, "precision": 0},
               "PROT":  {"type":  "U16", "index": {None: 0x0100}, "dp": None, "precision": 0},
               "BPS":   {"type":  "U16", "index": {None: 0x0101}, "dp": None, "precision": 0},
               "A.LEN": {"type":  "U16", "index": {None: 0x0102}, "dp": None, "precision": 0},
               "ADDR":  {"type":  "U16", "index": {None: 0x0103}, "dp": None, "precision": 0},
               "RSDL":  {"type":  "U16", "index": {None: 0x0104}, "dp": None, "precision": 0},
               "LEN":   {"type":  "U16", "index": {None: 0x0105}, "dp": None, "precision": 0},
               "PRTY":  {"type":  "U16", "index": {None: 0x0106}, "dp": None, "precision": 0},
               "SBIT":  {"type":  "U16", "index": {None: 0x0107}, "dp": None, "precision": 0},
               "N.ERR": {"type":  "U16", "index": {None: 0x0108}, "dp": None, "precision": 0},
               "PRTL":  {"type":  "U16", "index": {None: 0x0109}, "dp": None, "precision": 0},
               "APLY":  {"type":  "U16", "index": {None: 0x010A}, "dp": None, "precision": 0},
               "INIT":  {"type":  "U16", "index": {None: 0x010B}, "dp": None, "precision": 0},
               "INP2":  {"type":  "U16", "index": {None: 0x0300}, "dp": None, "precision": 0},
               "CALC":  {"type":  "U16", "index": {None: 0x0301}, "dp": None, "precision": 0},
               "KPV1":  {"type":  "I16", "index": {None: 0x0302}, "dp": None, "precision": 2},
               "KPV2":  {"type":  "I16", "index": {None: 0x0303}, "dp": None, "precision": 2},
               "SL-L":  {"type":  "I16", "index": {None: 0x0304}, "dp": "DP", "precision": 0},
               "SL-H":  {"type":  "I16", "index": {None: 0x0305}, "dp": "DP", "precision": 0},
               "OREU":  {"type":  "U16", "index": {None: 0x0306}, "dp": None, "precision": 0},
               "PV0":   {"type":  "I16", "index": {None: 0x0307}, "dp": None, "precision": 0},
               "RAMP":  {"type":  "U16", "index": {None: 0x0308}, "dp": None, "precision": 0},
               "P":     {"type":  "U16", "index": {None: 0x0309}, "dp": "DP", "precision": 0},
               "I":     {"type":  "U16", "index": {None: 0x030A}, "dp": None, "precision": 0},
               "D":     {"type":  "U16", "index": {None: 0x030B}, "dp": None, "precision": 0},
               "DB":    {"type":  "U16", "index": {None: 0x030C}, "dp": "DP", "precision": 0},
               "VSP":   {"type":  "U16", "index": {None: 0x030D}, "dp": "DP", "precision": 0},
               "OL-L":  {"type":  "U16", "index": {None: 0x030E}, "dp": None, "precision": 0},
               "OL-H":  {"type":  "U16", "index": {None: 0x030F}, "dp": None, "precision": 0},
               "LBA":   {"type":  "U16", "index": {None: 0x0310}, "dp": None, "precision": 0},
               "LBAB":  {"type":  "U16", "index": {None: 0x0311}, "dp": "DP", "precision": 0},
               "MVER":  {"type":  "U16", "index": {None: 0x0312}, "dp": None, "precision": 0},
               "MVST":  {"type":  "U16", "index": {None: 0x0313}, "dp": None, "precision": 0},
               "MDST":  {"type":  "U16", "index": {None: 0x0314}, "dp": None, "precision": 0},
               "ALT":   {"type":  "U16", "index": {None: 0x0315}, "dp": None, "precision": 0},
               "AL-D":  {"type":  "U16", "index": {None: 0x0316}, "dp": "DP", "precision": 0},
               "AL-H":  {"type":  "U16", "index": {None: 0x0317}, "dp": "DP", "precision": 0},
               "V.MOT": {"type":  "U16", "index": {None: 0x0400}, "dp": None, "precision": 0},
               "V.DB":  {"type":  "U16", "index": {None: 0x0401}, "dp": None, "precision": 0},
               "V.GAP": {"type":  "U16", "index": {None: 0x0402}, "dp": None, "precision": 1},
               "V.REV": {"type":  "U16", "index": {None: 0x0403}, "dp": None, "precision": 1},
               "V.TOF": {"type":  "U16", "index": {None: 0x0404}, "dp": None, "precision": 0},
               "RET":   {"type":  "U16", "index": {None: 0x0500}, "dp": None, "precision": 0},
               "DIS1":  {"type":  "U16", "index": {None: 0x0501}, "dp": None, "precision": 0},
               "DIS2":  {"type":  "U16", "index": {None: 0x0502}, "dp": None, "precision": 0},
               "DIS3":  {"type":  "U16", "index": {None: 0x0503}, "dp": None, "precision": 0},
               "DIS4":  {"type":  "U16", "index": {None: 0x0504}, "dp": None, "precision": 0},
               "DIS5":  {"type":  "U16", "index": {None: 0x0505}, "dp": None, "precision": 0},
               "NODE":  {"type":  "U16", "index": {None: 0x0600}, "dp": None, "precision": 0},
               "OAPT":  {"type":  "U16", "index": {None: 0x0700}, "dp": None, "precision": 0},
               "WTPT":  {"type":  "U16", "index": {None: 0x0701}, "dp": None, "precision": 0},
               "EDPT":  {"type":  "U16", "index": {None: 0x0702}, "dp": None, "precision": 0},
               "PV":    {"type":  "F32", "index": {0: 0x1009, 1: 0x100B}, "dp": None, "precision": 0},
               "IN.T":  {"type":  "U16", "index": {0: 0x0200, 1: 0x020A}, "dp": None, "precision": 0},
               "DPT":   {"type":  "U16", "index": {0: 0x0201, 1: 0x020B}, "dp": None, "precision": 0},
               "DP":    {"type":  "U16", "index": {0: 0x0202, 1: 0x020C}, "dp": None, "precision": 0},
               "IN.L":  {"type":  "I16", "index": {0: 0x0203, 1: 0x020D}, "dp": "DP", "precision": 0},
               "IN.H":  {"type":  "I16", "index": {0: 0x0204, 1: 0x020E}, "dp": "DP", "precision": 0},
               "SH":    {"type":  "I16", "index": {0: 0x0205, 1: 0x020F}, "dp": "DP", "precision": 0},
               "KU":    {"type":  "U16", "index": {0: 0x0206, 1: 0x0210}, "dp": None, "precision": 3},
               "FB":    {"type":  "U16", "index": {0: 0x0207, 1: 0x0211}, "dp": "DP", "precision": 0},
               "INF":   {"type":  "U16", "index": {0: 0x0208, 1: 0x0212}, "dp": None, "precision": 0},
               "SQR":   {"type":  "U16", "index": {0: 0x0209, 1: 0x0213}, "dp": None, "precision": 0},
               "X":     {"type":  "I16", "index": {1: 0x0601, 2: 0x0603, 3: 0x0605, 4: 0x0607, 5: 0x0609, 6: 0x060B, 7: 0x060D, 8: 0x060F, 9: 0x0611, 10: 0x0613}, "dp": "DP", "precision": 0},
               "Y":     {"type":  "I16", "index": {1: 0x0602, 2: 0x0604, 3: 0x0606, 4: 0x0608, 5: 0x060A, 6: 0x060C, 7: 0x060E, 8: 0x0610, 9: 0x0612, 10: 0x0614}, "dp": "DP", "precision": 0},
              },
    "byteorder": ">",
    "wordorder": ">",
}
