#! /usr/bin/env python
# -*- coding: utf-8 -*-

# Назначение полей таблиц настроек:
#   1. Тип протокола Owen
#       * Название параметра (в верхнем регистре)
#           - Тип параметра
#           - Список поддерживаемых индексов (None - индекса нет; 0,1 и т.д)
#           - Минимальное значение параметра
#           - Максимальное значение параметра
#   2. Тип протокола Modbus
#       * Название параметра (в верхнем регистре)
#           - Тип параметра
#           - Словарь поддерживаемых индексов (None - индекса нет; 0,1 и т.д) + адрес Modbus
#           - Минимальное значение параметра
#           - Максимальное значение параметра
#           - Кортеж, содержащий признак зависимости значения от другого параметра и его название
#           - Кол-во знаков после запятой


# Таблица настроек измерителя-ПИД-регулятора ТРМ101
TRM101 = {'Owen': {'PV':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SP':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'R-S':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AT':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'O':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'IN-T':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 26},
                   'DPT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DP':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 3},
                   'IN-L':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'IN-H':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SL-L':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SL-H':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SH':    {'type': 'F24', 'index': [None,], 'min': -500,  'max': 500},
                   'KU':    {'type': 'F24', 'index': [None,], 'min': 0.500, 'max': 2.000},
                   'INF':   {'type': 'F24', 'index': [None,], 'min': 0,     'max': 999},
                   'FB':    {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'AN-L':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'AN-H':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'EV-1':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'ALT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 11},
                   'AL-D':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'AL-H':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'OREU':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'CP':    {'type': 'U8',  'index': [None,], 'min': 1,     'max': 250},
                   'VSP':   {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'CNTL':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'HYST':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'ONST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ONER':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'RAMP':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'P':     {'type': 'F24', 'index': [None,], 'min': 0.001, 'max': 9999},
                   'I':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 3999},
                   'D':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 3999},
                   'DB':    {'type': 'F24', 'index': [None,], 'min': 0,     'max': 200},
                   'OL-L':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'OL-H':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'ORL':   {'type': 'F24', 'index': [None,], 'min': 0.2,   'max': 100},
                   'MVER':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'MVST':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'MDST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'LBA':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9999},
                   'LBAB':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'ADDR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'RSDL':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 45},
                   'A.LEN': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'BPS':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'LEN':   {'type': 'U8',  'index': [None,], 'min': 1,     'max': 1},
                   'PRTY':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 0},
                   'SBIT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 0},
                   'VER':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'DEV':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'APLY':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'INIT':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'N.ERR': {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                   'ATTR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'O-ED':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'O.':    {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'EDPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                  },
         }

# Таблица настроек измерителя-регулятора шестиканального ТРМ136
TRM136 = {'Owen': {'IND.T':  {'type': 'U16', 'index': [None,], 'min': 1,     'max': 600},
                   'IND.R':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 60},
                   'IND.A':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AL.DR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 6},
                   'AL.HD':  {'type': 'U16', 'index': [None,], 'min': 1,     'max': 600},
                   'AL.ST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'CJ-.C':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'SYST':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'BL.AR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'IN.FD':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 15},
                   'PRT':    {'type': 'U16', 'index': [None,], 'min': 1,     'max': 6},
                   'IN.SH':  {'type': 'I16', 'index': [None,], 'min': -99.9, 'max': 999.9},
                   'IN.SL':  {'type': 'U16', 'index': [None,], 'min': 0.9,   'max': 1.1},
                   'IN-T':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 21},
                   'IN.FG':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 100},
                   'AIN.L':  {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'AIN.H':  {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'C.SP':   {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'HYST':   {'type': 'U16', 'index': [None,], 'min': 1,     'max': 9999},
                   'C.SP.O': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9999},
                   'HT.ON':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9000},
                   'HT.OF':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9000},
                   'DL.ON':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 3600},
                   'DL.OF':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 3600},
                   'BL.ST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DP_':    {'type': 'U16', 'index': [None,], 'min': 0,     'max': 3},
                   'ER.ST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AL.T':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 5},
                   'AO.L':   {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'AO.H':   {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'C.DR':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 6},
                   'C.LBT':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9000},
                   'AL.OU':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'C.LBA':  {'type': 'U16', 'index': [None,], 'min': 1,     'max': 100},
                   'C.IN':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 18},
                   'BPS':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'LEN':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PRTY':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'SBIT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'A.LEN':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ADDR':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2040},
                   'N.FLT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'DATA':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 7},
                   'T.INC':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'CHAR':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'SOUR':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'READ':   {'type': 'F32', 'index': [None,], 'min': -2**127, 'max': 2**127},
                   'DR.DG':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1},
                   'N.ERR':  {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                  },
         }

# Таблица настроек измерителя-регулятора восьмиканального ТРМ138
TRM138 = {'Owen': {'IND.T':  {'type': 'U16', 'index': [None,], 'min': 1,     'max': 600},
                   'IND.R':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 60},
                   'IND.A':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AL.DR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 8},
                   'AL.HD':  {'type': 'U16', 'index': [None,], 'min': 1,     'max': 600},
                   'AL.ST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'CJ-.C':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'SYST':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'BL.AR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'IN.FD':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 15},
                   'PRT':    {'type': 'U16', 'index': [None,], 'min': 1,     'max': 8},
                   'IN.SH':  {'type': 'I16', 'index': [None,], 'min': -99.9, 'max': 999.9},
                   'IN.SL':  {'type': 'U16', 'index': [None,], 'min': 0.9,   'max': 1.1},
                   'IN-T':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 21},
                   'IN.FG':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 100},
                   'AIN.L':  {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'AIN.H':  {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'C.SP':   {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'HYST':   {'type': 'U16', 'index': [None,], 'min': 1,     'max': 9999},
                   'C.SP.O': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9999},
                   'HT.ON':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9000},
                   'HT.OF':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9000},
                   'DL.ON':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 3600},
                   'DL.OF':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 3600},
                   'BL.ST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DP_':    {'type': 'U16', 'index': [None,], 'min': 0,     'max': 3},
                   'ER.ST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AL.T':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 5},
                   'AO.L':   {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'AO.H':   {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'C.DR':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 8},
                   'C.LBT':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9000},
                   'AL.OU':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'C.LBA':  {'type': 'U16', 'index': [None,], 'min': 1,     'max': 100},
                   'C.IN':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 19},
                   'BPS':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'LEN':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PRTY':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'SBIT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'A.LEN':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ADDR':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2040},
                   'N.FLT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'DATA':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 7},
                   'T.INC':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'CHAR':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'SOUR':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'READ':   {'type': 'F32', 'index': [None,], 'min': -2**127, 'max': 2**127},
                   'DR.DG':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1},
                   'N.ERR':  {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                  },
         }

# Таблица настроек ТРМ151
TRM151 = {'Owen': {'READ':  {'type': 'F32', 'index': [None,], 'min': -9999, 'max': 9999},
                   'R.CAL': {'type': 'F32', 'index': [0, 1, 2, 3, 4, 5, 6, 7], 'min': -9999, 'max': 9999},
                   'RD.RG': {'type': 'F32', 'index': [0, 1, 2, 3, 4, 5, 6, 7], 'min': 0,     'max': 1},
                   'R.OUT': {'type': 'F32', 'index': [0, 1],  'min': -1,    'max': 1},
                   'SET.P': {'type': 'F32', 'index': [0, 1, 2, 3, 4, 5, 6, 7], 'min': -999,  'max': 9999},
                   'R.KEY': {'type': 'U16', 'index': [0, 1, 2, 3, 4, 5, 6, 7], 'min': 0,     'max': 1},
                   'R.PRG': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1},
                   'R.STP': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1},
                   'R.ST':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1},
                   'R.S':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2},
                  },
         }

# Таблица настроек измерителя двухканального ТРМ200
TRM200 = {'Owen': {'PV':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'LUPV':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'IN.T':  {'type': 'U8',  'index': [0, 1],  'min': 1,     'max': 26},
                   'DPT':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'DP':    {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 3},
                   'IN.L':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'IN.H':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'SQR':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'ILU':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 2},
                   'SH':    {'type': 'F24', 'index': [0, 1],  'min': -500,  'max': 500},
                   'KU':    {'type': 'F24', 'index': [0, 1],  'min': 0.500, 'max': 2.000},
                   'FB':    {'type': 'F24', 'index': [0, 1],  'min': 0,     'max': 9999},
                   'INF':   {'type': 'F24', 'index': [0, 1],  'min': 0,     'max': 999},
                   'REST':  {'type': 'U8',  'index': [None,], 'min': 5,     'max': 100},
                   'PROT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'BPS':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'A.LEN': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ADDR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'RSDL':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 45},
                   'LEN':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PRTY':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 0},
                   'SBIT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'VER':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'DEV':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'PRTL':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'APLY':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'INIT':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'N.ERR': {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                   'ATTR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'OAPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'WTPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'EDPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                  },
          'Modbus': {'STAT':  {'type': 'U16', 'index': {None: 0x0000,},        'min': 0,     'max': 65535, 'dp': (False, None), 'precision': 0},
                     'PV':    {'type': 'I16', 'index': {0: 0x0001, 1: 0x0002}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'LUPV':  {'type': 'I16', 'index': {0: 0x0003, 1: 0x0004}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'DEV':   {'type': 'STR', 'index': {None: 0x1000,},        'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'VER':   {'type': 'STR', 'index': {None: 0x1004,},        'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'PROT':  {'type': 'U16', 'index': {None: 0x0100,},        'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'BPS':   {'type': 'U16', 'index': {None: 0x0101,},        'min': 0,     'max': 8,     'dp': (False, None), 'precision': 0},
                     'A.LEN': {'type': 'U16', 'index': {None: 0x0102,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'ADDR':  {'type': 'U16', 'index': {None: 0x0103,},        'min': 0,     'max': 2047,  'dp': (False, None), 'precision': 0},
                     'RSDL':  {'type': 'U16', 'index': {None: 0x0104,},        'min': 0,     'max': 45,    'dp': (False, None), 'precision': 0},
                     'LEN':   {'type': 'U16', 'index': {None: 0x0105,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'PRTY':  {'type': 'U16', 'index': {None: 0x0106,},        'min': 0,     'max': 0,     'dp': (False, None), 'precision': 0},
                     'SBIT':  {'type': 'U16', 'index': {None: 0x0107,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'N.ERR': {'type': 'U16', 'index': {None: 0x0108,},        'min': 0,     'max': 255,   'dp': (False, None), 'precision': 0},
                     'PRTL':  {'type': 'U16', 'index': {None: 0x0109,},        'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'APLY':  {'type': 'U16', 'index': {None: 0x010A,},        'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'INIT':  {'type': 'U16', 'index': {None: 0x010B,},        'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'IN.T':  {'type': 'U16', 'index': {0: 0x0200, 1: 0x020B}, 'min': 1,     'max': 26,    'dp': (False, None), 'precision': 0},
                     'DPT':   {'type': 'U16', 'index': {0: 0x0201, 1: 0x020C}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'DP':    {'type': 'U16', 'index': {0: 0x0202, 1: 0x020D}, 'min': 0,     'max': 3,     'dp': (False, None), 'precision': 0},
                     'IN.L':  {'type': 'I16', 'index': {0: 0x0203, 1: 0x020E}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'IN.H':  {'type': 'I16', 'index': {0: 0x0204, 1: 0x020F}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SH':    {'type': 'I16', 'index': {0: 0x0205, 1: 0x0210}, 'min': -500,  'max': 500,   'dp': (True, 'DP'),  'precision': 0},
                     'KU':    {'type': 'U16', 'index': {0: 0x0206, 1: 0x0211}, 'min': 0.5,   'max': 2.0,   'dp': (False, None), 'precision': 3},
                     'FB':    {'type': 'U16', 'index': {0: 0x0207, 1: 0x0212}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'INF':   {'type': 'U16', 'index': {0: 0x0208, 1: 0x0213}, 'min': 0,     'max': 999,   'dp': (False, None), 'precision': 0},
                     'SQR':   {'type': 'U16', 'index': {0: 0x0209, 1: 0x0214}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'ILU':   {'type': 'U16', 'index': {0: 0x020A, 1: 0x0215}, 'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'REST':  {'type': 'U16', 'index': {None: 0x0300,},        'min': 5,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'OAPT':  {'type': 'U16', 'index': {None: 0x0700,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'WTPT':  {'type': 'U16', 'index': {None: 0x0701,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'EDPT':  {'type': 'U16', 'index': {None: 0x0702,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                    },
         }

# Таблица настроек измерителя-регулятора одноканального ТРМ201
TRM201 = {'Owen': {'PV':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SP':    {'type': 'F24', 'index': [0,],    'min': -1999, 'max': 9999},
                   'IN.T':  {'type': 'U8',  'index': [0,],    'min': 1,     'max': 26},
                   'DPT':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 1},
                   'DP':    {'type': 'U8',  'index': [0,],    'min': 0,     'max': 3},
                   'IN.L':  {'type': 'F24', 'index': [0,],    'min': -1999, 'max': 9999},
                   'IN.H':  {'type': 'F24', 'index': [0,],    'min': -1999, 'max': 9999},
                   'SQR':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 1},
                   'SH':    {'type': 'F24', 'index': [0,],    'min': -500,  'max': 500},
                   'KU':    {'type': 'F24', 'index': [0,],    'min': 0.500, 'max': 2.000},
                   'FB':    {'type': 'F24', 'index': [0,],    'min': 0,     'max': 9999},
                   'INF':   {'type': 'F24', 'index': [0,],    'min': 0,     'max': 999},
                   'REST':  {'type': 'U8',  'index': [None,], 'min': 5,     'max': 100},
                   'SL.L':  {'type': 'F24', 'index': [0,],    'min': -1999, 'max': 9999},
                   'SL.H':  {'type': 'F24', 'index': [0,],    'min': -1999, 'max': 9999},
                   'CMP':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 4},
                   'HYS':   {'type': 'F24', 'index': [0,],    'min': 0,     'max': 9999},
                   'DON':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 250},
                   'DOF':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 250},
                   'TON':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 250},
                   'TOF':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 250},
                   'DAC':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 1},
                   'CTL':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 1},
                   'XP':    {'type': 'F24', 'index': [0,],    'min': 0.002, 'max': 9999},
                   'AN.L':  {'type': 'F24', 'index': [0,],    'min': -1999, 'max': 9999},
                   'AN.H':  {'type': 'F24', 'index': [0,],    'min': -1999, 'max': 9999},
                   'OER':   {'type': 'U8',  'index': [0,],    'min': 0,     'max': 1},
                   'PROT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'BPS':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'A.LEN': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ADDR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'RSDL':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 45},
                   'LEN':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PRTY':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 0},
                   'SBIT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'VER':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'DEV':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'PRTL':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'APLY':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'INIT':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'N.ERR': {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                   'ATTR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R-L':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R.OUT': {'type': 'F24', 'index': [None,], 'min': 0,     'max': 1},
                   'OAPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'WTPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'EDPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                  },
          'Modbus': {'STAT':  {'type': 'U16', 'index': {None: 0x0000,}, 'min': 0,     'max': 65535, 'dp': (False, None), 'precision': 0},
                     'PV':    {'type': 'I16', 'index': {None: 0x0001,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SP':    {'type': 'I16', 'index': {None: 0x0002,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'R-L':   {'type': 'U16', 'index': {None: 0x0003,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'R.OUT': {'type': 'U16', 'index': {None: 0x0004,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 3},
                     'DEV':   {'type': 'STR', 'index': {None: 0x1000,}, 'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'VER':   {'type': 'STR', 'index': {None: 0x1004,}, 'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'PROT':  {'type': 'U16', 'index': {None: 0x0100,}, 'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'BPS':   {'type': 'U16', 'index': {None: 0x0101,}, 'min': 0,     'max': 8,     'dp': (False, None), 'precision': 0},
                     'A.LEN': {'type': 'U16', 'index': {None: 0x0102,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'ADDR':  {'type': 'U16', 'index': {None: 0x0103,}, 'min': 0,     'max': 2047,  'dp': (False, None), 'precision': 0},
                     'RSDL':  {'type': 'U16', 'index': {None: 0x0104,}, 'min': 0,     'max': 45,    'dp': (False, None), 'precision': 0},
                     'LEN':   {'type': 'U16', 'index': {None: 0x0105,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'PRTY':  {'type': 'U16', 'index': {None: 0x0106,}, 'min': 0,     'max': 0,     'dp': (False, None), 'precision': 0},
                     'SBIT':  {'type': 'U16', 'index': {None: 0x0107,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'N.ERR': {'type': 'U16', 'index': {None: 0x0108,}, 'min': 0,     'max': 255,   'dp': (False, None), 'precision': 0},
                     'PRTL':  {'type': 'U16', 'index': {None: 0x0109,}, 'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'APLY':  {'type': 'U16', 'index': {None: 0x010A,}, 'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'INIT':  {'type': 'U16', 'index': {None: 0x010B,}, 'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'IN.T':  {'type': 'U16', 'index': {None: 0x0200,}, 'min': 1,     'max': 26,    'dp': (False, None), 'precision': 0},
                     'DPT':   {'type': 'U16', 'index': {None: 0x0201,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'DP':    {'type': 'U16', 'index': {None: 0x0202,}, 'min': 0,     'max': 3,     'dp': (False, None), 'precision': 0},
                     'IN.L':  {'type': 'I16', 'index': {None: 0x0203,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'IN.H':  {'type': 'I16', 'index': {None: 0x0204,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SH':    {'type': 'I16', 'index': {None: 0x0205,}, 'min': -500,  'max': 500,   'dp': (True, 'DP'),  'precision': 0},
                     'KU':    {'type': 'U16', 'index': {None: 0x0206,}, 'min': 0.5,   'max': 2.00,  'dp': (False, None), 'precision': 3},
                     'FB':    {'type': 'U16', 'index': {None: 0x0207,}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'INF':   {'type': 'U16', 'index': {None: 0x0208,}, 'min': 0,     'max': 999,   'dp': (False, None), 'precision': 0},
                     'SQR':   {'type': 'U16', 'index': {None: 0x0209,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'REST':  {'type': 'U16', 'index': {None: 0x0300,}, 'min': 5,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'SL.L':  {'type': 'I16', 'index': {None: 0x0400,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SL.H':  {'type': 'I16', 'index': {None: 0x0401,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'CMP':   {'type': 'U16', 'index': {None: 0x0402,}, 'min': 0,     'max': 4,     'dp': (False, None), 'precision': 0},
                     'HYS':   {'type': 'U16', 'index': {None: 0x0403,}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'DON':   {'type': 'U16', 'index': {None: 0x0404,}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'DOF':   {'type': 'U16', 'index': {None: 0x0405,}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'TON':   {'type': 'U16', 'index': {None: 0x0406,}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'TOF':   {'type': 'U16', 'index': {None: 0x0407,}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'OER':   {'type': 'U16', 'index': {None: 0x0408,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'DAC':   {'type': 'U16', 'index': {None: 0x0409,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'AN.L':  {'type': 'I16', 'index': {None: 0x040A,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'AN.H':  {'type': 'I16', 'index': {None: 0x040B,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'CTL':   {'type': 'U16', 'index': {None: 0x040C,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'XP':    {'type': 'U16', 'index': {None: 0x040D,}, 'min': 0.002, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'OAPT':  {'type': 'U16', 'index': {None: 0x0700,}, 'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'WTPT':  {'type': 'U16', 'index': {None: 0x0701,}, 'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'EDPT':  {'type': 'U16', 'index': {None: 0x0702,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                    },
         }

# Таблица настроек измерителя-регулятора двухканального ТРМ202
TRM202 = {'Owen': {'PV':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'LUPV':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SP':    {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'IN.T':  {'type': 'U8',  'index': [0, 1],  'min': 1,     'max': 26},
                   'DPT':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'DP':    {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 3},
                   'IN.L':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'IN.H':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'SQR':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'ILU':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 2},
                   'SH':    {'type': 'F24', 'index': [0, 1],  'min': -500,  'max': 500},
                   'KU':    {'type': 'F24', 'index': [0, 1],  'min': 0.500, 'max': 2.000},
                   'FB':    {'type': 'F24', 'index': [0, 1],  'min': 0,     'max': 9999},
                   'INF':   {'type': 'F24', 'index': [0, 1],  'min': 0,     'max': 999},
                   'DISP':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'REST':  {'type': 'U8',  'index': [None,], 'min': 5,     'max': 100},
                   'SL.L':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'SL.H':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'CMP':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 4},
                   'HYS':   {'type': 'F24', 'index': [0, 1],  'min': 0,     'max': 9999},
                   'DON':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 250},
                   'DOF':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 250},
                   'TON':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 250},
                   'TOF':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 250},
                   'DAC':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'CTL':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'XP':    {'type': 'F24', 'index': [0, 1],  'min': 0.002, 'max': 9999},
                   'AN.L':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'AN.H':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'OER':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'PROT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'BPS':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'A.LEN': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ADDR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'RSDL':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 45},
                   'LEN':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PRTY':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 0},
                   'SBIT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'VER':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'DEV':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'PRTL':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'APLY':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'INIT':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'N.ERR': {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                   'ATTR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R-L':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R.OUT': {'type': 'F24', 'index': [None,], 'min': 0,     'max': 1},
                   'OAPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'WTPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 3},
                   'EDPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                  },
          'Modbus': {'STAT':  {'type': 'U16', 'index': {None: 0x0000,},        'min': 0,     'max': 65535, 'dp': (False, None), 'precision': 0},
                     'PV':    {'type': 'I16', 'index': {0: 0x0001, 1: 0x0002}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'LUPV':  {'type': 'I16', 'index': {0: 0x0003, 1: 0x0004}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SP':    {'type': 'I16', 'index': {0: 0x0005, 1: 0x0006}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'R-L':   {'type': 'U16', 'index': {0: 0x0007, 1: 0x0008}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'R.OUT': {'type': 'U16', 'index': {0: 0x0009, 1: 0x000A}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 3},
                     'DEV':   {'type': 'STR', 'index': {None: 0x1000,},        'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'VER':   {'type': 'STR', 'index': {None: 0x1004,},        'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'PROT':  {'type': 'U16', 'index': {None: 0x0100,},        'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'BPS':   {'type': 'U16', 'index': {None: 0x0101,},        'min': 0,     'max': 8,     'dp': (False, None), 'precision': 0},
                     'A.LEN': {'type': 'U16', 'index': {None: 0x0102,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'ADDR':  {'type': 'U16', 'index': {None: 0x0103,},        'min': 0,     'max': 2047,  'dp': (False, None), 'precision': 0},
                     'RSDL':  {'type': 'U16', 'index': {None: 0x0104,},        'min': 0,     'max': 45,    'dp': (False, None), 'precision': 0},
                     'LEN':   {'type': 'U16', 'index': {None: 0x0105,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'PRTY':  {'type': 'U16', 'index': {None: 0x0106,},        'min': 0,     'max': 0,     'dp': (False, None), 'precision': 0},
                     'SBIT':  {'type': 'U16', 'index': {None: 0x0107,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'N.ERR': {'type': 'U16', 'index': {None: 0x0108,},        'min': 0,     'max': 255,   'dp': (False, None), 'precision': 0},
                     'PRTL':  {'type': 'U16', 'index': {None: 0x0109,},        'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'APLY':  {'type': 'U16', 'index': {None: 0x010A,},        'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'INIT':  {'type': 'U16', 'index': {None: 0x010B,},        'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'IN.T':  {'type': 'U16', 'index': {0: 0x0200, 1: 0x020B}, 'min': 1,     'max': 26,    'dp': (False, None), 'precision': 0},
                     'DPT':   {'type': 'U16', 'index': {0: 0x0201, 1: 0x020C}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'DP':    {'type': 'U16', 'index': {0: 0x0202, 1: 0x020D}, 'min': 0,     'max': 3,     'dp': (False, None), 'precision': 0},
                     'IN.L':  {'type': 'I16', 'index': {0: 0x0203, 1: 0x020E}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'IN.H':  {'type': 'I16', 'index': {0: 0x0204, 1: 0x020F}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SH':    {'type': 'I16', 'index': {0: 0x0205, 1: 0x0210}, 'min': -500,  'max': 500,   'dp': (True, 'DP'),  'precision': 0},
                     'KU':    {'type': 'U16', 'index': {0: 0x0206, 1: 0x0211}, 'min': 0.50,  'max': 2.00,  'dp': (False, None), 'precision': 3},
                     'FB':    {'type': 'U16', 'index': {0: 0x0207, 1: 0x0212}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'INF':   {'type': 'U16', 'index': {0: 0x0208, 1: 0x0213}, 'min': 0,     'max': 999,   'dp': (False, None), 'precision': 0},
                     'SQR':   {'type': 'U16', 'index': {0: 0x0209, 1: 0x0214}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'ILU':   {'type': 'U16', 'index': {0: 0x020A, 1: 0x0215}, 'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'REST':  {'type': 'U16', 'index': {None: 0x0300,},        'min': 5,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'DISP':  {'type': 'U16', 'index': {None: 0x0301,},        'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'SL.L':  {'type': 'I16', 'index': {0: 0x0400, 1: 0x040E}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SL.H':  {'type': 'I16', 'index': {0: 0x0401, 1: 0x040F}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'CMP':   {'type': 'U16', 'index': {0: 0x0402, 1: 0x0410}, 'min': 0,     'max': 4,     'dp': (False, None), 'precision': 0},
                     'HYS':   {'type': 'U16', 'index': {0: 0x0403, 1: 0x0411}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'DON':   {'type': 'U16', 'index': {0: 0x0404, 1: 0x0412}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'DOF':   {'type': 'U16', 'index': {0: 0x0405, 1: 0x0413}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'TON':   {'type': 'U16', 'index': {0: 0x0406, 1: 0x0414}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'TOF':   {'type': 'U16', 'index': {0: 0x0407, 1: 0x0415}, 'min': 0,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'OER':   {'type': 'U16', 'index': {0: 0x0408, 1: 0x0416}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'DAC':   {'type': 'U16', 'index': {0: 0x0409, 1: 0x0417}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'AN.L':  {'type': 'I16', 'index': {0: 0x040A, 1: 0x0418}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'AN.H':  {'type': 'I16', 'index': {0: 0x040B, 1: 0x0419}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'CTL':   {'type': 'U16', 'index': {0: 0x040C, 1: 0x041A}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'XP':    {'type': 'U16', 'index': {0: 0x040D, 1: 0x041B}, 'min': 0.002, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'OAPT':  {'type': 'U16', 'index': {None: 0x0700,},        'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'WTPT':  {'type': 'U16', 'index': {None: 0x0701,},        'min': 0,     'max': 3,     'dp': (False, None), 'precision': 0},
                     'EDPT':  {'type': 'U16', 'index': {None: 0x0702,},        'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                    },
         }

# Таблица настроек измерителя-ПИД-регулятора ТРМ210
TRM210 = {'Owen': {'PV':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SP':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'R-S':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AT':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'O':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'IN-T':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 26},
                   'DPT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DP':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 3},
                   'IN-L':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'IN-H':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SL-L':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SL-H':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SH':    {'type': 'F24', 'index': [None,], 'min': -500,  'max': 500},
                   'KU':    {'type': 'F24', 'index': [None,], 'min': 0.500, 'max': 2.000},
                   'INF':   {'type': 'F24', 'index': [None,], 'min': 0,     'max': 999},
                   'FB':    {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'AN-L':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'AN-H':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'EV-1':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'ALT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 11},
                   'AL-D':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'AL-H':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'OREU':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'CP':    {'type': 'U8',  'index': [None,], 'min': 1,     'max': 250},
                   'VSP':   {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'CNTL':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'HYST':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'ONST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ONER':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'RAMP':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'P':     {'type': 'F24', 'index': [None,], 'min': 0.001, 'max': 9999},
                   'I':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 3999},
                   'D':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 3999},
                   'DB':    {'type': 'F24', 'index': [None,], 'min': 0,     'max': 200},
                   'OL-L':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'OL-H':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'ORL':   {'type': 'F24', 'index': [None,], 'min': 0.2,   'max': 100},
                   'MVER':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'MVST':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'MDST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'LBA':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9999},
                   'LBAB':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'PROT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'ADDR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'RSDL':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 45},
                   'A.LEN': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'BPS':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'LEN':   {'type': 'U8',  'index': [None,], 'min': 1,     'max': 1},
                   'PRTY':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 0},
                   'SBIT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'VER':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'DEV':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'PRTL':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'APLY':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'INIT':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'N.ERR': {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                   'ATTR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R-L':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R.OUT': {'type': 'F24', 'index': [None,], 'min': 0,     'max': 1},
                   'EDPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                  },
          'Modbus': {'STAT':  {'type': 'U16', 'index': {None: 0x0000,}, 'min': 0,     'max': 65535, 'dp': (False, None), 'precision': 0},
                     'PV':    {'type': 'I16', 'index': {None: 0x0001,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SP':    {'type': 'I16', 'index': {None: 0x0002,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SET.P': {'type': 'I16', 'index': {None: 0x0003,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'O':     {'type': 'U16', 'index': {None: 0x0004,}, 'min': 0,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'R-L':   {'type': 'U16', 'index': {None: 0x0005,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'R.OUT': {'type': 'U16', 'index': {None: 0x0006,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 3},
                     'R-S':   {'type': 'U16', 'index': {None: 0x0007,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'AT':    {'type': 'U16', 'index': {None: 0x0008,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'DEV':   {'type': 'STR', 'index': {None: 0x1000,}, 'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'VER':   {'type': 'STR', 'index': {None: 0x1004,}, 'min': "",    'max': "",    'dp': (False, None), 'precision': 0},
                     'PROT':  {'type': 'U16', 'index': {None: 0x0100,}, 'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'BPS':   {'type': 'U16', 'index': {None: 0x0101,}, 'min': 0,     'max': 8,     'dp': (False, None), 'precision': 0},
                     'A.LEN': {'type': 'U16', 'index': {None: 0x0102,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'ADDR':  {'type': 'U16', 'index': {None: 0x0103,}, 'min': 0,     'max': 2047,  'dp': (False, None), 'precision': 0},
                     'RSDL':  {'type': 'U16', 'index': {None: 0x0104,}, 'min': 0,     'max': 45,    'dp': (False, None), 'precision': 0},
                     'LEN':   {'type': 'U16', 'index': {None: 0x0105,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'PRTY':  {'type': 'U16', 'index': {None: 0x0106,}, 'min': 0,     'max': 0,     'dp': (False, None), 'precision': 0},
                     'SBIT':  {'type': 'U16', 'index': {None: 0x0107,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'N.ERR': {'type': 'U16', 'index': {None: 0x0108,}, 'min': 0,     'max': 255,   'dp': (False, None), 'precision': 0},
                     'PRTL':  {'type': 'U16', 'index': {None: 0x0109,}, 'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'APLY':  {'type': 'U16', 'index': {None: 0x010A,}, 'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'INIT':  {'type': 'U16', 'index': {None: 0x010B,}, 'min': 1,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'IN-T':  {'type': 'U16', 'index': {None: 0x0200,}, 'min': 1,     'max': 26,    'dp': (False, None), 'precision': 0},
                     'DPT':   {'type': 'U16', 'index': {None: 0x0201,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'DP':    {'type': 'U16', 'index': {None: 0x0202,}, 'min': 0,     'max': 3,     'dp': (False, None), 'precision': 0},
                     'IN-L':  {'type': 'I16', 'index': {None: 0x0203,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'IN-H':  {'type': 'I16', 'index': {None: 0x0204,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SH':    {'type': 'I16', 'index': {None: 0x0205,}, 'min': -500,  'max': 500,   'dp': (True, 'DP'),  'precision': 0},
                     'KU':    {'type': 'U16', 'index': {None: 0x0206,}, 'min': 0.5,   'max': 2.0,   'dp': (False, None), 'precision': 3},
                     'FB':    {'type': 'U16', 'index': {None: 0x0207,}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'INF':   {'type': 'U16', 'index': {None: 0x0208,}, 'min': 0,     'max': 999,   'dp': (False, None), 'precision': 0},
                     'SL-L':  {'type': 'I16', 'index': {None: 0x0300,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'SL-H':  {'type': 'I16', 'index': {None: 0x0301,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'OREU':  {'type': 'U16', 'index': {None: 0x0302,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'CNTL':  {'type': 'U16', 'index': {None: 0x0303,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'CP':    {'type': 'U16', 'index': {None: 0x0304,}, 'min': 1,     'max': 250,   'dp': (False, None), 'precision': 0},
                     'RAMP':  {'type': 'U16', 'index': {None: 0x0305,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'P':     {'type': 'U16', 'index': {None: 0x0306,}, 'min': 1,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'I':     {'type': 'U16', 'index': {None: 0x0307,}, 'min': 0,     'max': 3999,  'dp': (False, None), 'precision': 0},
                     'D':     {'type': 'U16', 'index': {None: 0x0308,}, 'min': 0,     'max': 3999,  'dp': (False, None), 'precision': 0},
                     'DB':    {'type': 'U16', 'index': {None: 0x0309,}, 'min': 0,     'max': 200,   'dp': (True, 'DP'),  'precision': 0},
                     'VSP':   {'type': 'U16', 'index': {None: 0x030A,}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'OL-L':  {'type': 'U16', 'index': {None: 0x030B,}, 'min': 0,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'OL-H':  {'type': 'U16', 'index': {None: 0x030C,}, 'min': 0,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'ORL':   {'type': 'U16', 'index': {None: 0x030D,}, 'min': 0.2,   'max': 100,   'dp': (False, None), 'precision': 1},
                     'MVER':  {'type': 'U16', 'index': {None: 0x030E,}, 'min': 0,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'MDST':  {'type': 'U16', 'index': {None: 0x030F,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'MVST':  {'type': 'U16', 'index': {None: 0x0310,}, 'min': 0,     'max': 100,   'dp': (False, None), 'precision': 0},
                     'HYST':  {'type': 'U16', 'index': {None: 0x0311,}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'ONST':  {'type': 'U16', 'index': {None: 0x0312,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'ONER':  {'type': 'U16', 'index': {None: 0x0313,}, 'min': 0,     'max': 1,     'dp': (False, None), 'precision': 0},
                     'EV-1':  {'type': 'U16', 'index': {None: 0x0400,}, 'min': 0,     'max': 2,     'dp': (False, None), 'precision': 0},
                     'LBA':   {'type': 'U16', 'index': {None: 0x0401,}, 'min': 0,     'max': 9999,  'dp': (False, None), 'precision': 0},
                     'LBAB':  {'type': 'U16', 'index': {None: 0x0402,}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'ALT':   {'type': 'U16', 'index': {None: 0x0403,}, 'min': 0,     'max': 11,    'dp': (False, None), 'precision': 0},
                     'AL-D':  {'type': 'U16', 'index': {None: 0x0404,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'AL-H':  {'type': 'U16', 'index': {None: 0x0405,}, 'min': 0,     'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'AN-L':  {'type': 'I16', 'index': {None: 0x0406,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                     'AN-H':  {'type': 'I16', 'index': {None: 0x0407,}, 'min': -1999, 'max': 9999,  'dp': (True, 'DP'),  'precision': 0},
                    },
         }

# Таблица настроек измерителя-ПИД-регулятора ТРМ212
TRM212 = {'Owen': {'PV':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'LUPV':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SP':    {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'SET.P': {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 9999},
                   'R-S':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AT':    {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'O':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'IN.T':  {'type': 'U8',  'index': [0, 1],  'min': 1,     'max': 26},
                   'DPT':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 1},
                   'DP':    {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 3},
                   'IN.L':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'IN.H':  {'type': 'F24', 'index': [0, 1],  'min': -1999, 'max': 9999},
                   'SQR':   {'type': 'U8',  'index': [0, 1],  'min': 0,     'max': 2},
                   'SH':    {'type': 'F24', 'index': [0, 1],  'min': -500,  'max': 500},
                   'KU':    {'type': 'F24', 'index': [0, 1],  'min': 0.500, 'max': 2.000},
                   'FB':    {'type': 'F24', 'index': [0, 1],  'min': 0,     'max': 9999},
                   'INF':   {'type': 'F24', 'index': [0, 1],  'min': 0,     'max': 9999},
                   'INP2':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 4},
                   'CALC':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 34},
                   'KPV1':  {'type': 'F24', 'index': [None,], 'min': -19.99,'max': 99.99},
                   'KPV2':  {'type': 'F24', 'index': [None,], 'min': -19.99,'max': 99.99},
                   'SL-L':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 3000},
                   'SL-H':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 3000},
                   'OREU':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'RAMP':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PV0':   {'type': 'F24', 'index': [None,], 'min': -100,  'max': 2000},
                   'P':     {'type': 'F24', 'index': [None,], 'min': 0.001, 'max': 9999},
                   'I':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 3999},
                   'D':     {'type': 'F24', 'index': [None,], 'min': 0,     'max': 3999},
                   'KA':    {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'DB':    {'type': 'F24', 'index': [None,], 'min': 0,     'max': 200},
                   'VSP':   {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'OL-L':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'OL-H':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'MVER':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'MVST':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 100},
                   'MDST':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'LBA':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9999},
                   'LBAB':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'ALT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 14},
                   'AL-D':  {'type': 'F24', 'index': [None,], 'min': -1999, 'max': 3000},
                   'AL-H':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 3000},
                   'V.MOT': {'type': 'F24', 'index': [None,], 'min': 5,     'max': 999},
                   'V.DB':  {'type': 'F24', 'index': [None,], 'min': 0,     'max': 9999},
                   'V.GAP': {'type': 'F24', 'index': [None,], 'min': 0,     'max': 10},
                   'V.REV': {'type': 'F24', 'index': [None,], 'min': 0,     'max': 10},
                   'V.TOF': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 10},
                   'DIS1':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DIS2':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DIS3':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DIS4':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'DIS5':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'RET':   {'type': 'U8',  'index': [None,], 'min': 5,     'max': 100},
                   'NODE':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 10},
                   'X':     {'type': 'F24', 'index': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'min': -1999, 'max': 3000},
                   'Y':     {'type': 'F24', 'index': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'min': -1999, 'max': 3000},
                   'PROT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'BPS':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'A.LEN': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'ADDR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2047},
                   'RSDL':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 45},
                   'LEN':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PRTY':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 0},
                   'SBIT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'VER':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'DEV':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'PRTL':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'APLY':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'INIT':  {'type': 'U8',  'index': [None,], 'min': None,  'max': None},
                   'N.ERR': {'type': 'U24', 'index': [None,], 'min': 0,     'max': 255},
                   'ATTR':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R-L':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'R.OUT': {'type': 'F24', 'index': [None,], 'min': -1,    'max': 1},
                   'OAPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'WTPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 3},
                   'EDPT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                  },
          'Modbus': {'STAT':  {'type': 'U16', 'index': {None: 0x0000,},        'min': 0,     'max': 65535,  'dp': (False, None), 'precision': 0},
                     'PV':    {'type': 'I16', 'index': {0: 0x0001, 1: 0x0002}, 'min': -1999, 'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'LUPV':  {'type': 'I16', 'index': {None: 0x0003,},        'min': -1999, 'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'SP':    {'type': 'I16', 'index': {None: 0x0004,},        'min': -1999, 'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'SET.P': {'type': 'I16', 'index': {None: 0x0005,},        'min': -1999, 'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'O':     {'type': 'U16', 'index': {None: 0x0006,},        'min': 0,     'max': 100,    'dp': (False, None), 'precision': 0},
                     'R-L':   {'type': 'U16', 'index': {None: 0x0007,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'R.OUT': {'type': 'U16', 'index': {None: 0x0008,},        'min': -1.0,  'max': 1.0,    'dp': (False, None), 'precision': 3},
                     'R-S':   {'type': 'U16', 'index': {None: 0x0009,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'AT':    {'type': 'U16', 'index': {None: 0x000A,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'DEV':   {'type': 'STR', 'index': {None: 0x1000,},        'min': "",    'max': "",     'dp': (False, None), 'precision': 0},
                     'VER':   {'type': 'STR', 'index': {None: 0x1004,},        'min': "",    'max': "",     'dp': (False, None), 'precision': 0},
                     'PROT':  {'type': 'U16', 'index': {None: 0x0100,},        'min': 0,     'max': 2,      'dp': (False, None), 'precision': 0},
                     'BPS':   {'type': 'U16', 'index': {None: 0x0101,},        'min': 0,     'max': 8,      'dp': (False, None), 'precision': 0},
                     'A.LEN': {'type': 'U16', 'index': {None: 0x0102,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'ADDR':  {'type': 'U16', 'index': {None: 0x0103,},        'min': 0,     'max': 2047,   'dp': (False, None), 'precision': 0},
                     'RSDL':  {'type': 'U16', 'index': {None: 0x0104,},        'min': 0,     'max': 45,     'dp': (False, None), 'precision': 0},
                     'LEN':   {'type': 'U16', 'index': {None: 0x0105,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'PRTY':  {'type': 'U16', 'index': {None: 0x0106,},        'min': 0,     'max': 0,      'dp': (False, None), 'precision': 0},
                     'SBIT':  {'type': 'U16', 'index': {None: 0x0107,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'N.ERR': {'type': 'U16', 'index': {None: 0x0108,},        'min': 0,     'max': 255,    'dp': (False, None), 'precision': 0},
                     'PRTL':  {'type': 'U16', 'index': {None: 0x0109,},        'min': 1,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'APLY':  {'type': 'U16', 'index': {None: 0x010A,},        'min': 1,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'INIT':  {'type': 'U16', 'index': {None: 0x010B,},        'min': 1,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'IN.T':  {'type': 'U16', 'index': {0: 0x0200, 1: 0x020A}, 'min': 1,     'max': 26,     'dp': (False, None), 'precision': 0},
                     'DPT':   {'type': 'U16', 'index': {0: 0x0201, 1: 0x020B}, 'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'DP':    {'type': 'U16', 'index': {0: 0x0202, 1: 0x020C}, 'min': 0,     'max': 3,      'dp': (False, None), 'precision': 0},
                     'IN.L':  {'type': 'I16', 'index': {0: 0x0203, 1: 0x020D}, 'min': -1999, 'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'IN.H':  {'type': 'I16', 'index': {0: 0x0204, 1: 0x020E}, 'min': -1999, 'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'SH':    {'type': 'I16', 'index': {0: 0x0205, 1: 0x020F}, 'min': -500,  'max': 500,    'dp': (True, 'DP'),  'precision': 0},
                     'KU':    {'type': 'U16', 'index': {0: 0x0206, 1: 0x0210}, 'min': 0.5,   'max': 2.0,    'dp': (False, None), 'precision': 3},
                     'FB':    {'type': 'U16', 'index': {0: 0x0207, 1: 0x0211}, 'min': 0,     'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'INF':   {'type': 'U16', 'index': {0: 0x0208, 1: 0x0212}, 'min': 0,     'max': 999,    'dp': (False, None), 'precision': 0},
                     'SQR':   {'type': 'U16', 'index': {0: 0x0209, 1: 0x0213}, 'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'INP2':  {'type': 'U16', 'index': {None: 0x0300,},        'min': 0,     'max': 4,      'dp': (False, None), 'precision': 0},
                     'CALC':  {'type': 'U16', 'index': {None: 0x0301,},        'min': 0,     'max': 3,      'dp': (False, None), 'precision': 0},
                     'KPV1':  {'type': 'I16', 'index': {None: 0x0302,},        'min': -19.99,'max': 99.99,  'dp': (False, None), 'precision': 2},
                     'KPV2':  {'type': 'I16', 'index': {None: 0x0303,},        'min': -19.99,'max': 99.99,  'dp': (False, None), 'precision': 2},
                     'SL-L':  {'type': 'I16', 'index': {None: 0x0304,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'SL-H':  {'type': 'I16', 'index': {None: 0x0305,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'OREU':  {'type': 'U16', 'index': {None: 0x0306,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'PV0':   {'type': 'I16', 'index': {None: 0x0307,},        'min': -100,  'max': 2000,   'dp': (False, None), 'precision': 0},
                     'RAMP':  {'type': 'U16', 'index': {None: 0x0308,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'P':     {'type': 'U16', 'index': {None: 0x0309,},        'min': 1,     'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'I':     {'type': 'U16', 'index': {None: 0x030A,},        'min': 0,     'max': 3999,   'dp': (False, None), 'precision': 0},
                     'D':     {'type': 'U16', 'index': {None: 0x030B,},        'min': 0,     'max': 3999,   'dp': (False, None), 'precision': 0},
                     'DB':    {'type': 'U16', 'index': {None: 0x030C,},        'min': 0,     'max': 200,    'dp': (True, 'DP'),  'precision': 0},
                     'VSP':   {'type': 'U16', 'index': {None: 0x030D,},        'min': 0,     'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'OL-L':  {'type': 'U16', 'index': {None: 0x030E,},        'min': 0,     'max': 100,    'dp': (False, None), 'precision': 0},
                     'OL-H':  {'type': 'U16', 'index': {None: 0x030F,},        'min': 0,     'max': 100,    'dp': (False, None), 'precision': 0},
                     'LBA':   {'type': 'U16', 'index': {None: 0x0310,},        'min': 0,     'max': 9999,   'dp': (False, None), 'precision': 0},
                     'LBAB':  {'type': 'U16', 'index': {None: 0x0311,},        'min': 0,     'max': 9999,   'dp': (True, 'DP'),  'precision': 0},
                     'MVER':  {'type': 'U16', 'index': {None: 0x0312,},        'min': 0,     'max': 100,    'dp': (False, None), 'precision': 0},
                     'MVST':  {'type': 'U16', 'index': {None: 0x0313,},        'min': 0,     'max': 100,    'dp': (False, None), 'precision': 0},
                     'MDST':  {'type': 'U16', 'index': {None: 0x0314,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'ALT':   {'type': 'U16', 'index': {None: 0x0315,},        'min': 0,     'max': 14,     'dp': (False, None), 'precision': 0},
                     'AL-D':  {'type': 'U16', 'index': {None: 0x0316,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'AL-H':  {'type': 'U16', 'index': {None: 0x0317,},        'min': 0,     'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'V.MOT': {'type': 'U16', 'index': {None: 0x0400,},        'min': 5,     'max': 999,    'dp': (False, None), 'precision': 0},
                     'V.DB':  {'type': 'U16', 'index': {None: 0x0401,},        'min': 0,     'max': 9999,   'dp': (False, None), 'precision': 0},
                     'V.GAP': {'type': 'U16', 'index': {None: 0x0402,},        'min': 0,     'max': 10,     'dp': (False, None), 'precision': 1},
                     'V.REV': {'type': 'U16', 'index': {None: 0x0403,},        'min': 0,     'max': 10,     'dp': (False, None), 'precision': 1},
                     'V.TOF': {'type': 'U16', 'index': {None: 0x0404,},        'min': 0,     'max': 10,     'dp': (False, None), 'precision': 0},
                     'RET':   {'type': 'U16', 'index': {None: 0x0500,},        'min': 5,     'max': 100,    'dp': (False, None), 'precision': 0},
                     'DIS1':  {'type': 'U16', 'index': {None: 0x0501,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'DIS2':  {'type': 'U16', 'index': {None: 0x0502,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'DIS3':  {'type': 'U16', 'index': {None: 0x0503,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'DIS4':  {'type': 'U16', 'index': {None: 0x0504,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'DIS5':  {'type': 'U16', 'index': {None: 0x0505,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                     'NODE':  {'type': 'U16', 'index': {None: 0x0600,},        'min': 1,     'max': 10,     'dp': (False, None), 'precision': 0},
                     'X1':    {'type': 'I16', 'index': {None: 0x0601,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y1':    {'type': 'I16', 'index': {None: 0x0602,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X2':    {'type': 'I16', 'index': {None: 0x0603,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y2':    {'type': 'I16', 'index': {None: 0x0604,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X3':    {'type': 'I16', 'index': {None: 0x0605,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y3':    {'type': 'I16', 'index': {None: 0x0606,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X4':    {'type': 'I16', 'index': {None: 0x0607,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y4':    {'type': 'I16', 'index': {None: 0x0608,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X5':    {'type': 'I16', 'index': {None: 0x0609,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y5':    {'type': 'I16', 'index': {None: 0x060A,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X6':    {'type': 'I16', 'index': {None: 0x060B,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y6':    {'type': 'I16', 'index': {None: 0x060C,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X7':    {'type': 'I16', 'index': {None: 0x060D,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y7':    {'type': 'I16', 'index': {None: 0x060E,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X8':    {'type': 'I16', 'index': {None: 0x060F,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y8':    {'type': 'I16', 'index': {None: 0x0610,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X9':    {'type': 'I16', 'index': {None: 0x0611,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y9':    {'type': 'I16', 'index': {None: 0x0612,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'X10':   {'type': 'I16', 'index': {None: 0x0613,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'Y10':   {'type': 'I16', 'index': {None: 0x0614,},        'min': -1999, 'max': 3000,   'dp': (True, 'DP'),  'precision': 0},
                     'OAPT':  {'type': 'U16', 'index': {None: 0x0700,},        'min': 0,     'max': 2,      'dp': (False, None), 'precision': 0},
                     'WTPT':  {'type': 'U16', 'index': {None: 0x0701,},        'min': 0,     'max': 4,      'dp': (False, None), 'precision': 0},
                     'EDPT':  {'type': 'U16', 'index': {None: 0x0702,},        'min': 0,     'max': 1,      'dp': (False, None), 'precision': 0},
                    },
         }

# Таблица настроек измерителя-регулятора ТРМ251
TRM251 = {'Owen': {'VER':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'DEV':   {'type': 'STR', 'index': [None,], 'min': "",    'max': ""},
                   'CJ-.C': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'IN.RE': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'IN-T':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 36},
                   'IN.FD': {'type': 'U16', 'index': [0, 1,], 'min': 0,     'max': 1800},
                   'IN.FG': {'type': 'U16', 'index': [0, 1,], 'min': 0,     'max': 9999},
                   'ITRL':  {'type': 'U16', 'index': [0, 1,], 'min': 0.3,   'max': 30},
                   'IN.SH': {'type': 'I16', 'index': [0, 1,], 'min': -999,  'max': 9999},
                   'IN.SL': {'type': 'U16', 'index': [0, 1,], 'min': 0.9,   'max': 1.1},
                   'AIN.L': {'type': 'I16', 'index': [0, 1,], 'min': -999,  'max': 9999},
                   'AIN.H': {'type': 'I16', 'index': [0, 1,], 'min': -999,  'max': 9999},
                   'REG.T': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'PB':    {'type': 'U16', 'index': [None,], 'min': 0.001, 'max': 9999},
                   'TI':    {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1092},
                   'TD.TI': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 0.3},
                   'I.UPR': {'type': 'I16', 'index': [None,], 'min': -100,  'max': 100},
                   'I.MIN': {'type': 'I16', 'index': [None,], 'min': -100,  'max': 100},
                   'P.NOM': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 100},
                   'P.UPR': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 100},
                   'P.MIN': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 100},
                   'P.STP': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 100},
                   'P.RES': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1000},
                   'HYS.C': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 9999},
                   'DEL':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 200},
                   'HOLD':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 200},
                   'YO':    {'type': 'I16', 'index': [None,], 'min': -9999, 'max': 9999},
                   'YDOP':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 999},
                   'POU':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'THP':   {'type': 'U8',  'index': [None,], 'min': 1,     'max': 81},
                   'T.L':   {'type': 'F24', 'index': [None,], 'min': 0.05,  'max': 0.5},
                   'RG.ON': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'AO.L':  {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'AO.H':  {'type': 'I16', 'index': [None,], 'min': -999,  'max': 9999},
                   'SP':    {'type': 'I16', 'index': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], 'min': -999,  'max': 9999},
                   'T.RS':  {'type': 'U16', 'index': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], 'min': 0,     'max': 1092},
                   'T.STB': {'type': 'U16', 'index': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], 'min': 0,     'max': 1092},
                   'SIG.T': {'type': 'U8',  'index': [0, 1, 2], 'min': 0,   'max': 1},
                   'S.H':   {'type': 'U16', 'index': [0, 1, 2], 'min': 0,   'max': 9999},
                   'S.L':   {'type': 'U16', 'index': [0, 1, 2], 'min': 0,   'max': 9999},
                   'LBA':   {'type': 'U8',  'index': [0, 1, 2], 'min': 0,   'max': 1},
                   'D.LBA': {'type': 'U16', 'index': [0, 1, 2], 'min': 0.001, 'max': 9999},
                   'T.LBA': {'type': 'U16', 'index': [0, 1, 2], 'min': 0.001, 'max': 9999},
                   'BPS':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 8},
                   'LEN':   {'type': 'U8',  'index': [None,], 'min': 7,     'max': 8},
                   'PRTY':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'SBIT':  {'type': 'U8',  'index': [None,], 'min': 1,     'max': 2},
                   'A.LEN': {'type': 'U8',  'index': [None,], 'min': 8,     'max': 11},
                   'ADDR':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 2040},
                   'PROT':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 2},
                   'DOT':   {'type': 'U8',  'index': [None,], 'min': 0,     'max': 3},
                   'RS.DL': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 50},
                   'BEHV':  {'type': 'U8',  'index': [None,], 'min': 0,     'max': 3},
                   'T.SCL': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'NET.S': {'type': 'U8',  'index': [None,], 'min': 0,     'max': 1},
                   'READ':  {'type': 'F32', 'index': [None,], 'min': -999,  'max': 9999},
                   'R.OUT': {'type': 'F32', 'index': [None,], 'min': 0,     'max': 1},
                   'R.SIG': {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1},
                   'RD.RG': {'type': 'F32', 'index': [None,], 'min': 0,     'max': 1},
                   'R.ST':  {'type': 'U16', 'index': [None,], 'min': 0,     'max': 7},
                   'R.PRG': {'type': 'U16', 'index': [None,], 'min': 1,     'max': 3},
                   'R.STP': {'type': 'U16', 'index': [None,], 'min': 1,     'max': 5},
                   'SET.P': {'type': 'F32', 'index': [None,], 'min': -999,  'max': 9999},
                   'R-S':   {'type': 'U16', 'index': [None,], 'min': 0,     'max': 1},
                  },
         }
